### ISSUE TITLE
deprecate key in favor of ref using a URN

### ISSUE THREAD

**Issue by mdalmau** [kshawkin/Best-Practices-for-TEI-in-Libraries#1]
The TEI Council, after discussing feature request 2919640, decided at its April 2010 meeting in Dublin to change the Guidelines to recommend use of @ref with a URN in place of @key. Revisions to P5 are forthcoming.
If we work this revision into the BP, we will probably need to revise our section on "key and ref" to something like:

```
<author><persName type="marc100" ref="lccn:n78-95332">Shakespeare, William, 1564-1616</persName></author>
```

Not sure whether use of `<taxonomy>` is still warranted.

**Comment by sydb** [comment]
Ha! Interesting that gitHub does not display the encoding on the issue page, but the e-mail copy I got does show the encoding.

In any case, the important question is do we want to try to re-word this section in the next 48 hours or whatever it is?

**Comment by mdalmau** [comment]
I entered it mostly as an exercise to test the user-friendliness of the
interface as well as to have an example in the queue for others who may
submit an issue.  I think it can remain as-is (copied straight from the wiki
page) for now.  I suspect normalizing how bugs are entered will be difficult
and probably not worth our time.  I didn't assign anyone to the issue either
until we come up with a plan for that as well.

Are you not going to Germany?

On Wed, Oct 12, 2011 at 4:43 AM, Syd Bauman <
reply@reply.github.com>wrote:

> Ha! Interesting that gitHub does not display the encoding on the issue
> page, but the e-mail copy I got does show the encoding.
> 
> In any case, the important question is do we want to try to re-word this
> section in the next 48 hours or whatever it is?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sydb/TEI-in-Libraries/issues/1#issuecomment-2377020

## 

|  Michelle Dalmau, Digital Projects & Usability Librarian
|  Indiana University Digital Library Program
|  Herman B Wells Library
|  1320 East 10th Street, W501
|  Bloomington, Indiana 47405
|  (812) 855-1261, mdalmau@indiana.edu
|  http://mypage.iu.edu/~mdalmau/

**Comment by sydb** [comment]
Yes, in Germany. Haven't seen John yet, though.

> I entered it mostly as an exercise to test the user-friendliness of
> the interface as well as to have an example in the queue for others
> who may submit an issue. I think it can remain as-is (copied
> straight from the wiki page) for now. I suspect normalizing how
> bugs are entered will be difficult and probably not worth our time.
> I didn't assign anyone to the issue either until we come up with a
> plan for that as well.
> 
> Are you not going to Germany?

**Comment by kshawkin** [comment]
The change to use of @ref with a URN instead of @key never got implemented, it seems.  However, the issue has come up again: see http://purl.org/TEI/fr/3437509 .

**Comment by kshawkin** [comment]
The situation in P5 has developed since this issue was opened, so I've created a new one ( https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/5 ) and will close this one.
