### ISSUE TITLE
indicating interviewers and interviewees

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#10]
Consider this suggestion from Syd Bauman ...

Section “Level 4 Oral History” currently recommends that the speaking participants in the interview be identified as authors of the document, or in profileDesc/particDesc/list/item/name. In the example encoding of this interviewees and interviewers are differentiated as text inside the given `<item>`. This strikes me as sloppy. It may well be appropriate to permit this encoding, in case someone is digitizing hundreds of interviews and has OCRed metadata that lists the participants this way. But certainly a best practice would make use of `<listPerson>`, and explicitly indicate "interviewer", "interviewee", "thirdParty" (or whatever) on the role= of `<person>`, no?

**Comment by kshawkin** [comment]
During BPTL workgroup call today, we agreed to implement according to Syd's recommendation. No volunteer to implement yet.

**Comment by sydb** [comment]
Add `<listPerson>` and `<person>` (with `@role`) to level 4, including in table of elements. Also include `<birth>`; maybe `<langKnown>`?
@arouner to work on prose (either by posting here or in prose of level4.odd); @sydb will work on schema.

**Comment by sydb** [comment]
Level 4 schema is fixed (at 828328c8b0ac229de7bf21a11fe61df63aae09d7) to have `<listPerson>`, `<person>` (with `@role`), and `<birth>`. I did not add `<langKnown>`. The table in level _4.2.5.5. Element Recommendations for Level 4_ includes all of these elements plus the wrapper `<langKnowledge>`, so we have a bit of a discrepancy that needs to be fixed.

The prose and example in _4.2.5.6.5. Level 4 Oral History_ is, well, screwy. Looks like it may have been partially fixed, and then forgotten. (For sure, I’m not blaming anyone, it well may have been me.)

**Comment by kshawkin** [comment]
During BPTL call today, agreed to remove `<langKnown>` and `<langKnowledge>` from Level 4 table and schema because they're too specialized for Level 4.

**Comment by sydb** [comment]
Removed `<langKnowledge>` and `<langKnown>` form schema & table at 688e9e4.

**Comment by emylonas** [comment]
Has the prose in http://paramedic.wwp.northeastern.edu/~syd/temp/BPTL/main-driver.html#index.xml-body.1_div.4_div.2_div.5_div.6_div.5 been checked? It's not as clear as it  might be.

**Comment by kshawkin** [comment]
Checked with respect to the schema changes, or just edited for general clarity?  If the latter, we could let it get covered by #44 , but if you have specific suggestions for clarification, feel free to commit changes or do a pull request!

**Comment by emylonas** [comment]
It can wait until #44. I think the bullet format for the list of options was a little confusing to me. It's more overall proofreading than problems reflecting the schema change.  also typo "poiints"

**Comment by kshawkin** [comment]
Got it.  Typo now fixed: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/82b7103ee38158bda7a3e0437223a07e16539cf7 .  Will close this issue.
