### ISSUE TITLE
encoding <pb>s within <note>s

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#11]
Give guidance on encoding of `<pb/>`s within `<note>`s. Should these be encoded or omitted, with the `<note>` element appearing in the XML "within" the page on which it began? (Note that the BP allows for local practice in gathering all notes for a given section to a div at the end of the section.)
If encoding such `<pb/>`s will be optional or required, there will generally be two instances of `<pb n="X"/>` every time a note crosses a page boundary. Should we recommend use of `@sameAs` or `@corresp` to indicate that you are encoding the same page break twice? See this thread on TEI-L: https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;78bc9c43.1011 .

**Comment by emylonas** [comment]
Recommend encoding of `<pb>` in both text and note, and use @sameAs on each element to point to the other. implement when there is opportunity.
This is should definitely be added to the prose, check for @sameAs in ODD.

**Comment by sydb** [comment]
`@sameAs` exists in levels 4 and 3; it does not currently exist in 2 and 1.

**Comment by kshawkin** [comment]
During the BPTL call on 2017-02-13, Syd agreed to implement this.

**Comment by emylonas** [comment]
instead of adding `@sameas`, remove `<note>` from the body of level 1 and 2

**Comment by sydb** [comment]
Per today’s conference call, seems like `@sameAs` is all set, but we want a constraint so that `<note>` is not permitted outside of header.

**Comment by sydb** [comment]
Addressed at 953fc48
