### ISSUE TITLE
bibliographies and other lists of works cited

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#12]
We give no guidance on encoding bibliographies, lists of works cited, lists of references, and other such things in documents. In TEI, you would use listBibl for this. We need to decide:
1. Whether to include this in the BP and at which level.
2. Whether to use bibl, biblStruct, or biblFull inside the list. (I strongly argue for bibl to give you the necessary flexibility to faithfully encode source documents.)
3. Since listBibl can include a head, the listBibl element could be a sibling of a div in TEI. However, this would go against the BP, which says to use divs for everything. So should listBibl go inside a div? If so, should the head be a child of listBibl (as in TEI) or of the div (to be consistent with other parts of the BP)?

**Comment by pcgorman** [comment]
1. Yes - at least level 4, possibly 3 and up.
2. I agree w/ bibl, for the reason stated, and also for the simpler workflow.
3. I'd argue that listBibl go inside a div, and have the header go with the div instead of the listBibl. There is often text intervening between the head and the list.

**Comment by emylonas** [comment]
Sep. 2016 work group discussion - agree with Peter's comment above
Recommendation, at level 3, put bibliography and refs in a `<div type="bibliography">`, with `<listBibl>` which will contain `<bibl>`s with no further detail marked. 
Open question - what do is the Level 4 recommendation? how much detail within `<bibl>` to have at that level. No decision yet.

**Comment by emylonas** [comment]
Level 4: require Author or editor of whole work, title and date. Can have access to the rest of the elements that can appear within `<bibl>`.

Note that for level 3, may want to allow some phrase level elements inside `<bibl>`

need to do prose and schema

**Comment by kshawkin** [comment]
Elli's comment above is what we decided during BPTL call on 2017-02-13.  We also decided to require use of `@when` on `<date>`.

Note that in the table of elements for Level 4, we use "recommended" for thing that are required and "optional" for things that are not required.  This is because, as described in the introduction:

> As guidelines rather than a specification, these _Best Practices_ use _should_ instead of _must_ in nearly all cases (except where a practice is required by P5), with optional practices indicated by _may_. However, to encourage conformance to these _Best Practices_, the ODD files will generate schemas that _require_ use of recommended elements (indicated by _should_).

However, this could change based on how we resolve https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/52 .

Still need to assign to someone to implement.

**Comment by emylonas** [comment]
## How to proceed
### Level 3: 

- Add information about `@type="bibliography"` in Element Recommendations for Level 3 `<div>`
- Add section 4.2.4.6.5 on how to encode bibliography - 
    - note that it can appear in `body` ( if attached to a chapter, for ex.) or `back`.  
    -  `<head>` should be in the `div`and not the `listBibl`. 
    - no further bibliographic markup appears inside the `<bibl>`. 
    - Phrase level elements such as `hi` can appear, however. 
- Add appropriate elements to schema ( listBibl, bibl) - these seem to already be there for level 4.

### Level 4: 
- Remove `<listBibl>` from the table of elements.
- Add `bibl` and indicate that it should contain bibliographic sub-elements
-no need to change the schema

**Comment by sydb** [comment]
Fixed at f1f222d.
