### ISSUE TITLE
update to take into account RDA

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#13]
The BP refers to "national cataloging codes" such that it could be used outside of the Anglo-American world.  However, some examples relating to AACR2 are given.  Now that this has largely been superseded by RDA, we need to update references ... and, if applicable, update MARC mappings and other practices that may have been affected by the move to RDA.  Still, we should try as best we can to stick to ISBD terminology rather than anything specific to RDA (or to AACR2).

**Comment by stuartyeates** [comment]
I think an explicit discussion of RDA and it's impact is needed.

**Comment by kshawkin** [comment]
During the BPTL call today, I agreed to ask a colleague to help with this.

**Comment by kshawkin** [comment]
My colleague Adam Baron is still on board and says he'll begin work on this now and will follow up with me by mid-October at the latest.

**Comment by kshawkin** [comment]
I've rewritten the discussion of `<analytic>` and `<monogr>` to account for the rare case of analytic catalog records.  See changes here: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/3586f8dc20af0447b2691fe6751695bcc5495519 .  These changes should be taken into account; in other words, I believe we could actually include mappings for the children of `<analytic>`.

**Comment by kshawkin** [comment]
Nudged my colleague about this today ...

**Comment by kshawkin** [comment]
Nudged again ...

**Comment by kshawkin** [comment]
I met with my colleague on 2017-05-06 and made a lot of progress, including on correcting MARC mappings.  Have compiled all proposed changes and asked him to verify.

**Comment by kshawkin** [comment]
Nudged my colleague today to see if he wants to verify the changes or if we should go ahead and implement.

**Comment by kshawkin** [comment]
Let's assume that we'll move ahead.  I've attached a DOCX file with track changes showing what we agreed upon.  Syd agreed to do the drudge work of implementing this (THANK YOU!), so I'm reassigning to him.

Syd, if you have trouble viewing the file in OpenOffice (I've found that OpenOffice does better with DOC than DOCX, let me know and I'll send email in that format.  (GitHub won't let me upload DOC format.)

[BPTL-header-revisions-with-Adam.docx](https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/files/1157834/BPTL-header-revisions-with-Adam.docx)

**Comment by sydb** [comment]
Done at commit db6ed0f

**Issues**

* section 4.1.5, para 1: I encoded “International Standard Bibliographic Description” and “Resource Description and Access” as `<title>`s, with the abbreviation following in parens, copying previous practice.
* Ibid, “… that has replaces the Anglo-American …”: changed “replaces” to “replaced”.
* The table row `<title type="___">` has the line “For all, use the relation designator ‘author’.”, but I bet that line belongs in the next row (“`<author>`”)
* The table row  `<date when="___">` now says `Use the <att>when</att> attribute (see <ref target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.w3c.html">att.datable.w3c class</ref>) to aid machine processing. This element has no content.` (I.e., I changed the URL to a `<ref>`.) But I object. If it has no content, then `@when` isn’t there to aid machine processing, it is there to store the date.
* Table rows `<pubPlace>` and `<publisher>`: I changed “such as” to “e.g.”.
* Table row `<date> or <date> or <date>`: I changed “as” to “e.g.” (the “such” was missing).
* Table row `<schemaRef key="___">`: How is the encoder supposed to know “how the TEI document is presented to the user”?
* Passim: changed some `<code>` to `<eg>`.
* Table row `<change when="YYYY-MM-DD" who="[URI]">`: 1) This is the only column that puts a signature or clue into the attr value template part. 2) I changed “a URI reference and not an ID/IDREF reference, and thus is not checked by validation software.” to “a URI, not an IDREF, and thus is typically not checked by validation software.”

**Comment by kshawkin** [comment]
During the BPTL call on 2017-08-28, I thanked Syd for his close reading of the changes while making these edits.  I agreed to review his notes above before closing this issue.

**Comment by kshawkin** [comment]
Following up on Syd's notes, everything is fine, though I note the following corrections and additional comments.

> The table row <title type="___"> has the line “For all, use the relation designator ‘author’.”, but I bet that line belongs in the next row (“<author>”)

Correct, it is supposed to be in the row for `<author>`.

> The table row <date when="___"> now says Use the <att>when</att> attribute (see <ref target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.w3c.html">att.datable.w3c class</ref>) to aid machine processing. This element has no content. (I.e., I changed the URL to a <ref>.) But I object. If it has no content, then @when isn’t there to aid machine processing, it is there to store the date.

This was shorthand for "Use the `@when` attribute (see att.datable.w3c class) instead of free text as content of the element to aim machine processing".  I'm open to a suggestion for a more precise wording.

> Table row <schemaRef key="___">: How is the encoder supposed to know “how the TEI document is presented to the user”?

The encoder may not, but the cataloger (or person implementing the metadata crosswalk) should know.

**Comment by sydb** [comment]
OK. At b8a86d4 I've moved the “For all, use …” to the `<author>` row, and re-worded the comment about `@when` of `<date>` inside `<publicationStmt>`.

**Comment by kshawkin** [comment]
We've added `listRelation` to the header table, but we need to check whether this has any mapping to MARC.  I'll ask my colleague.

**Comment by kshawkin** [comment]
After consultation, it seems that "n/a" was actually appropriate.  Will add back in.
