### ISSUE TITLE
how to record non-ASCII characters

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#14]
People often want to know what to do with non-ASCII characters. There are generally four options:
- insert them as they are (and assume the files will be manipulated by Unicode-aware software and that people can distinguish these from similar characters)
- insert decimal entity references
- insert hexadecimal entity references
- insert mneumonic entity references (which need to be declared)

We should give advice on this.

**Comment by stuartyeates** [comment]
http://www.w3.org/TR/REC-xml/ says:

  All XML processors MUST accept the UTF-8 and UTF-16 encodings of Unicode; ...

We should point to this and recommend using UTF-8, because in not requiring BOM it's simpler than UTF-16.

**Comment by dmj** [comment]
@kshawkin A fifth option is &lt;g> for characters from the private use area (PUA) and are not defined by Unicode. I think it helps to discuss the options with regard to groups of non-ASCII characters: precomposed characters, combining characters and characters from a PUA.
- precomposed characters: Enter as-is
- combining characters: Use numeric character references because using them as-is can cause serious visual distortions if the editiing environment (as shown below) ![optischer-fehler-unicode-combining](https://cloud.githubusercontent.com/assets/58969/15985399/043c7b54-2fec-11e6-858c-93569ade9a30.png)
- PUA: Use &lt;g> and a &lt;charDecl>

From what I know numeric character references and mnemonic general parsed entity references don't necessarily survive a roundtrip through XML software. That's something an end use should be aware of, too.

**Comment by kshawkin** [comment]
Right, it might good to give different recommendations for (a) glyphs that are available as precomposed Unicode characters, (b) glyphs that can only be constructed using combining characters, and (c) glyphs not in Unicode.  For the last one, it's true that I left `<g>` off the list.  Though I wasn't explicit about it when creating the issue, I was only talking about characters that are in Unicode—that is, (a) and (b).  The BPTL doesn't address the need to encode non-Unicode characters, though perhaps it should.

The BPTL, like P5, avoids recommendations that are software dependent, but we sometimes do it when the recommendation seems applicable to many programs and to broader digital library architectures (like what we say about always putting `<pb>`s and other milestone elements inside text divisions).  While it has long seemed that editing tools would soon improve their display of combining characters, maybe that won't really happen anytime soon, and therefore we should include the recommendation to use NCRs for combining characters.

I believe that XML software is required by the XML specification to handle NCRs, though people may end up editing files with software that doesn't implement the specification.  Aside the predefined mnemonic entity references (`&quot;`, `&lt;`, etc.), all other mnemonic entity references these have to be defined properly to be used, and I think you're right that they are more likely to not be processed properly.  While we don't currently discuss these in the BPTL, we could be explicit in recommending against their use.

**Comment by dmj** [comment]
To clarify re NCRs: What I mean is that they are processed properly but it depends on the XML processing software whether or not they are preserved. E.g. in an XSL transformation NCRs and entity references are replaced by the referenced and _not_ serialized as NCRs/entities back in the output document.

Re PUA: Maybe a simple note suffices. You can detect these characters with a regexp or schematron rule, the treatment is out of scope.

**Comment by dmj** [comment]
Now that I think about it: The distinction between as-is, character references and entities seems to become irrelevant as soon as you assume documents that are processed programmatically. And this starts with loading TEI documents into and accessing them via e.g. an XML database. Maybe the advice is: Use Unicode, preferably UTF-8 without a BOM and don't worry?

**Comment by kshawkin** [comment]
During today's BPTL discussion, we agreed that it is best not to discuss input or QC of character data (since needs can vary from one project and toolchain to another) but rather only discuss the format used for exchange and archiving, which is what's implicit in the BPTL.  We agreed to recommend use of UTF-8 (without a BOM) and not address entity references.  We'll also caution against overzealous capturing of glyph variants not distinguished by Unicode.  And we'll refer to http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html for further reading.

I volunteered to draft some prose on this.

**Comment by lb42** [comment]
The implication that &lt;g> is intended _only_ for PUA characters (if intended) is faulty. You can use &lt;g> for any character or glyph you wish to distinguish in your markup. The _content_ of the &lt;g> element may or may not be a PUA character.

**Comment by kshawkin** [comment]
Draft prose to be inserted between section 3.1 ("Standards and Local Practice") and section 3.2 ("Transcription"):

```
<div type="===">
  <head>Character Encoding</head>
  <p>To aid in interchange, TEI documents should be saved in UTF-8 format, without beginning 
with a byte-order mark (U+FEFF). Furthermore, while TEI allows for capturing of glyph variants 
not distinguished by Unicode (see 
<ref target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html">P5 chapter 5</ref>), the 
special elements for this purpose are not recommended in these <title>Best Practices</title> in 
order to facilitate interchange.</p>
</div>
```

I'm not sure that the second sentence is warranted since the introduction to the BPTL already says, "Only those elements and attributes mentioned below are recommended for use in encoding based on these Best Practices; use of other TEI elements and attributes is not recommended."

**Comment by kshawkin** [comment]
During today's BPTL call, Elli and Syd agreed to review my prose.

**Comment by kshawkin** [comment]
Elli and Syd like, except they suggest changing "To aid in interchange" to "For the purpose of interchange,".  I'll implement.

**Comment by kshawkin** [comment]
Done: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/cb03a7224c363b4895955b36f1d65a1f27c47038 .
