### ISSUE TITLE
give guidance on encoding serials and composite documents

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#16]
People often ask how to handle encoding of serials. Should you have a single TEI document for the whole journal run, for individual volumes, for individual issues, or for individual articles? How do you encode metadata about the serial as a whole, issues, and article?

Similarly, how do you handle composite documents like a volume of conference papers? (see an [example of such a question](https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;7aafda22.1209))? or a book of poems ( see an example of [such a question](https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;119ec446.1408))?

We should give advice on this.

**Comment by kshawkin** [comment]
See also https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;e9063cfb.1511 .

**Comment by kshawkin** [comment]
During the BPTL call on 2017-04-03, we decided that we'd recommend encoding an entire volume or issue as a single TEI document in Levels 1 and 2 but recommend encoding individual articles as single TEI documents in Levels 3 and 4.  I will propose a solution to implement this for consideration by the group.

**Comment by kshawkin** [comment]
Recommend adding a second paragraph to section 3.3. ("Transcription"):

> When encoding composite documents (an issue of a journal, a volume of conference papers, a book of poems, etc.) at Level 3 and above, consider creating separate TEI documents for each unit (journal article, conference paper, poem, etc.). This is a way to allow for richer metadata to be attached to each unit in its TEI header.  However, care will need to be taken to ensure that the structure of the composite document—how the units relate to each other—is adequately represented.  One way to accomplish this is to create a separate TEI document for the composite document that uses XInclude to include the relevant portions of the TEI documents for the units.

**Comment by kshawkin** [comment]
Elli will tweak prose and implement.

**Comment by emylonas** [comment]
Edited.

**Comment by emylonas** [comment]
close with b4bb36a

**Comment by emylonas** [comment]
removing `or URI references` for clarity
closing with 7dfb1ef
