### ISSUE TITLE
how to indicate conformance to the BP?

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#17]
In TEI, you typically use editorialDecl to say things about your specific use of the TEI. In the BP we use editorialDecl@n to say which encoding level you follow. And we have various p elements to describe encoding practices. But we have no place in the TEI document itself to record that the value of editorialDecl@n refers to the BP or that you follow the BP at all. We really should have this.

You could refer to a schema using http://www.w3.org/TR/xml-model/ , but we still need a mechanism to point to the ODD and/or prose documentation. This is part of a larger problem in the TEI.

**Comment by kshawkin** [comment]
Note that some think that a document should never name its schema (and, by extension, conformance to the BP or to any encoding levels), and if the document does, you shouldn't trust it.  See summary at http://www.biglist.com/lists/lists.mulberrytech.com/jats-list/archives/201509/msg00011.html .

**Comment by kshawkin** [comment]
Note that some the various `p` elements that describe encoding practices may be changed to specialized elements: see https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/9 .

**Comment by kshawkin** [comment]
BPTL group agreed that use of `editorial@n` to record the encoding level seems wrong, but we're not yet sure of a better way to do it.  We might just have boilerplate text in a `<p>` inside `<editorialDecl>`.  Elli and Stefanie will investigate and bring a proposal back to the group.

**Comment by kshawkin** [comment]
If we figure out a way to record that a document conforms to (or aspires to conform to) the BPTL, it would also be good if we could indicate which version of the BPTL it conforms to (or aspires to conform to).

**Comment by lb42** [comment]
Is BPTL a specific ODD/schema? If so the proposed &lt;schemaRef> is probably what you want. Or one of the other proposals discussed on https://github.com/TEIC/TEI/issues/564

**Comment by jrgriffiniii** [comment]
@lb42: How might encoding levels be addressed using the `<schemaRef>` element?

> Well, let us not quarrel about whether to call something a "classification or a "subtype" :-) I am just saying you could do @type="article" @subtype="simple" (or the other way round) and get what you need. The essential point is that this isn't a pointer to a specific instance of the ODD (that's what schemaRef would be if we had it) but a vague characterisation of the document instance. 
> [...]
> I revive my suggestion of a new <schemaRef> element with attributes @type (for vague categorisation)

If I accurately follow the thread within the referenced Issue, would it be best for one use either the @type or @subtype attribute values to capture such information?

**Comment by kshawkin** [comment]
BPTL discussed this again today.  Given that @lb42 helpfully pointed us to a pending ticket (https://github.com/TEIC/TEI/issues/564) before Council, the group decided to cancel the previous assignment for Elli and Stefanie to investigate and instead wait till Council recommends something.  Elli will report back to us on the status of this from discussions in Council.

**Comment by emylonas** [comment]
Sounds as if we should be waiting for schemaRef (which should be in next release, early December) and then put a line in the `<encodingDesc>` that will point to the appropriate ODD level.  - that means we should have URLs for all of these, as the syntax is: `<schemaRef url="">`.

**Comment by emylonas** [comment]
``<schemaRef>`` is all in P5 now. what URL do we point to? Options:

- github raw file of a release branch
-if this is to keep changing with new releases, the documentation has to explain what the current release and attribute value will be.
-some other place, still have to handle release number

**Comment by sydb** [comment]
I.e., something like
~~~~~xml
<schemaRef key="BPTL-L3-v3.1.0"/>
~~~~~

Also remember to remove the `@n` of `<editorialDecl>`.

**Comment by kshawkin** [comment]
During today's BPTL call, we discussed the issue and agreed to:

1) Add a row to the table of header elements for `<schemaRef>` (a child of `<editorialDec>`). For this element, say that you should use syntax like `key="BPTL-L3-v3.1.0"` to record that you are following a certain level of encoding in a certain version of the BPTL. You can also use `@url` to point to your own schema, whether a copy of one that follows the the BPTL exactly or a local customization.

2) Remove the discussion of using `@n` on `<editorialDecl>`.

Elli will still implement.

**Comment by sydb** [comment]
*Partially* implemented at dffbeb5ca583ec69c53158d8671e92ffac74683c: I’ve added `<schemaRef>` to the schema (with a suggested value list for `@key`), and changed all the examples I found. I did *not* remove the discussion of `@n` of `<editorialDecl>` (although I made it red inthe table), nor add a line for `<schemaRef>` to the table.

**Comment by kshawkin** [comment]
During the BPTL call on 2017-02-13, Syd and Elli agreed to collaborate on completing this.

**Comment by emylonas** [comment]
`@n` has been removed by @sydb
Elli adds line for schemaRef to the table.

**Comment by kshawkin** [comment]
A question related to this was accidentally posted under https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/45#issuecomment-281145071 .  Here's my response to that comment:

856 $z is used in MARC for text that should appear in a catalog record with the link to an online version.  Libraries may use standard statements like "Connect to online resource" or "Online version".  I believe that we had in mind that the cataloger might say something like "Pages images and searchable text" or "Encoded text" here to be more specific.  This is one of a number of things that will need to be revisited in the course of https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/13 .

**Comment by emylonas** [comment]
I am taking your response to mean that this is a valid piece of information and is correctly left in place in the table where we discuss schemaRef

**Comment by kshawkin** [comment]
Yes, at least for now.  Thanks!

**Comment by sydb** [comment]
Schema and prose done. However, current processing of PureODD still leaves us with an open set of values, rather than a lovely drop-down list, but that is (I think) a TEI problem.

**Comment by kshawkin** [comment]
@lb42 notes at https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/74#issuecomment-379791200 that we need to include url= on schemaRef, so reopening this issue.

**Comment by kshawkin** [comment]
Elli, Syd, and Kevin agreed that we should use url= instead of key= on schemaRef, giving a private URI scheme.  Kevin will update the syntax for the attribute value to "bptl:l1-v3.5.0a" etc.  Then Syd will check that this syntax is appropriate for a private URI scheme and then make corresponding schema changes.

**Comment by sydb** [comment]
Done at 92b1203 (mostly in 51f5f12).
Two further thoughts:
1. Although I was one of us who agreed on all lowercase letters, on looking at it I really think the “l” for “level” should be uppercase, e.g.: `bptl:L2-v4.0.0a`.
2. We need to at least have a prose `<remarks>` in the tagdoc for `<schemaRef>` that explains how a human should parse and understand these strings, if not a mandatory
~~~~~xml
      <listPrefixDef>
        <prefixDef
          ident="bptl"
          matchPattern="l([1-5])-v(\d+\.\d+\.\d+[aαβb]?)"
          replacementPattern="http://kevinH.example.lib/BPTL/version$2/L$1.nvdl"/>
      </listPrefixDef>
~~~~~
kinda thing in the `<encodingDesc>`.

**Comment by kshawkin** [comment]
Syd, thanks for doing my part of what we agreed to at https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/17#issuecomment-380457074 .  I agreed with your first suggestion and have already implemented.  As for the second, in the value of `@replacementPattern`, I would stick with "example.com" instead of "kevinH.example.lib" to avoid confusion.  But does this assume that someone creates an NVDL file?  If so, I think we'll need to explain this somewhere.

**Comment by sydb** [comment]
@kshawkin thinks we’ll end up using "http://www.tei-c.org/SIG/Libraries/teiinlibraries/4.0.0/" or some such.

**Comment by kshawkin** [comment]
Syd plans to return to this once he completes other work.

**Comment by kshawkin** [comment]
Elli, Syd, and I reviewed today; everything looks good.
