### ISSUE TITLE
update the tie to a specific version of P5

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#2]
When creating the BP, we decided to use @version="1.9.1" on `<TEI>` in the ODD files so that people could create schema at any point in the future without later changes to P5 creeping in, possibly contradicting the BP.  However, we will need to update the version number in order to incorporate some things we want to include in our revision.

To check what changes might come through when doing this, I recommend generating schemas for each level with the current ODDs (tied to version 1.9.1) and then updating the version number on a local copy to the current version number.  Compare the schema versions and see what changes appear.  If any of them warrant a mention in the prose of the BP, revise as necessary.

**Comment by kshawkin** [comment]
@sydb adds that removing `@version` isn't really an option since the Council frequently changes things that will break old ODDs.

**Comment by kshawkin** [comment]
Here are some of the things we might need to address: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/37

**Comment by lb42** [comment]
The correct way of   tieing your ODD to a specific release is to use the `@source` attribute on your `<schemaSpec>`.

**Comment by kshawkin** [comment]
Ah right, I was confused about this in 2011 and have had trouble getting it out of my head since then.  `TEI@version` is just a way of saying that the ODD was originally created based on that version of the TEI, not that the schemas should be generated from that particular version.  Tricky.

**Comment by sydb** [comment]
Right, Kevin. Lou is correct, and that is what we do. In general, our `TEI/@version` and our `schemaSpec/@source` indicate the same version of P5, although they don’t have to.

**Comment by sydb** [comment]
At commit 7f7f87c BP are now tied to P5 version 2.9.0.
Leaving this ticket open, though, as it is time to work on updating that to 3.0.0; or the ”Sinterklaas” release, which is scheduled for Tue 06 Dec 16.

**Comment by sydb** [comment]
The “Sinterklaas” edition, 3.1.0, is now scheduled for Thu 15 Dec 16. (And thus perhaps cannot be called “Sinterklaas” any more :-)

**Comment by sydb** [comment]
At commit dffbeb5ca583ec69c53158d8671e92ffac74683c BP are now tied to P5 version 3.1.10.
