### ISSUE TITLE
revised "display examples" for levels 3 and 4

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#20]
The display example for Level 3 has texts with lots of features not found in Level 3 and is of oral transcriptions, which don't have a clear source document. For clarity, I suggest we instead link to http://name.umdl.umich.edu/abu0246.0001.001 as a display example for Level 3 and http://webapp1.dlib.indiana.edu/vwwp/view?docId=VAB7020.xml for Level 4.

**Comment by kshawkin** [comment]
Workgroup agrees to implement this.  Elli will handle.

**Comment by emylonas** [comment]
I changed the URLs in the grid in the introductory paragraph - am also recommending that we select a worok in the Isaac Newton site, in order to actually go directly to a text and not to the home page of the project. Perhaps: http://webapp1.dlib.indiana.edu/newton/mss/dipl/ALCH00006/

**Comment by kshawkin** [comment]
BPTL group agreed with changing all URLs in "Display example" column to point to specific texts rather than to site homepages.

As we discussed today, feel free to commit directly to master branch.

**Comment by emylonas** [comment]
closed commit 94e9705
