### ISSUE TITLE
relation of BP to TEI simplePrint

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#23]
We need to figure out how [TEI Simple](https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_simple.odd) relates to the BP. At the very least we need to explain what it is and how it's different (as we did with TEI Tite). At the most, we recreate the BP as a customization of Simple or something.

**Comment by kshawkin** [comment]
Or maybe redefine Level 4 as the same as TEI Simple but with the BPTL header.

**Comment by lb42** [comment]
How does the BPTL header differ from the Simple header? Would be easy enough to make them the same, surely?

**Comment by kshawkin** [comment]
I'm only barely familiar with TEI Simple at this point, but as I recall, it has no header.  As for BPTL, it's header is quite detailed, with certain compromises from canonical TEI practice that are meant to allow for round-tripping with library catalog records stored in MARC format.

**Comment by lb42** [comment]
TEI SImple has a header. It would hardly be a TEI conformant schema if it did not. I'll take a look at BPTL header to see what  "compromises from canonical TEI practice" means!

**Comment by kshawkin** [comment]
Here's our statement from the BPTL: "In order to allow automatic generation of TEI headers from MARC records and MARC records from TEI headers, some elements (like <author>) contain content not typical for TEI practice but necessary due to a lack of granularity in the MARC format."  Since it's hard to read the table of header elements in `lib-header.odd`, you might want to consult this snapshot of the prose from the last release: http://www.tei-c.org/SIG/Libraries/teiinlibraries/main-driver.html#header-content .

But I wouldn't go too far quite yet: we've got an open issue to update AACR2 practices to RDA ( #13 ) that might change some things.

**Comment by lb42** [comment]
I compared the list of elements from the header module specified in the file lib-header.odd (version 3, oct 2011) with the list of elements proposed in the current version of TEI Simple, and have the following observations:
1. BPTL includes two elements excluded by Simple (application and appInfo)
2. Simple includes 14 elements excluded by BPTL , specifically:
   biblFull catDesc catRef category creation funder 
   licence listChange listPrefixDef prefixDef principal
   refsDecl sponsor and xenoData

Many  of these are newbies since 2011 so it's unsurprising that they're missing. I hope whoever is responsible for updating the BPTL will take them into account.

**Comment by kshawkin** [comment]
Yes, your list will be useful for work on #2 .

**Comment by kshawkin** [comment]
See this thread on teilib-l: https://list.indiana.edu/sympa/arc/teilib-l/2016-09/msg00003.html

**Comment by emylonas** [comment]
Clarify how BPTL is different from and related to Lite and Simple, as the BPTL already does for Tite. Create a new issue to hash out differences between Simple and Level 4, and approach Council if we feel that they need to be reconciled or make changes to BPTL level 4. 

Martin adds, perhaps also http://www.deutschestextarchiv.de/doku/basisformat_en

**Comment by kshawkin** [comment]
I'm not sure that we need to address how the BPTL differs from the DTA Base Format.  But I'll add a note to the new issue that we should consider the differences between Level 4 and the DTA Base Format.

**Comment by kshawkin** [comment]
Further to his comparison of lib-header.odd and TEI Simple above, Lou has also produced a comparison against P5: see https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/47 .  Just mentioning it here for completeness even though this ticket (unlike Lou's) is not really concerned with the header.

**Comment by kshawkin** [comment]
During the BPTL call on 2017-04-03, we decided to revise Level 5 to say that you might consider TEI simplePrint for your needs: #46 .  Given that, we should also revise the "Relationship to TEI Tite" section near the beginning of the BPTL to also discuss TEI simplePrint in brief.

I agreed to do this.

**Comment by kshawkin** [comment]
Implemented at https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/27527efbcb7aa728ad1d5f1e74d59cf0b3220e1e .
