### ISSUE TITLE
Cover MARC records and TEI body

### ISSUE THREAD

**Issue by stuartyeates** [kshawkin/Best-Practices-for-TEI-in-Libraries#25]
Certain MARC fields bear on the body of the text rather than the header (505, 520, etc) and these should be covered.

**Comment by stuartyeates** [comment]
I now have running XSL for this.  It's still in BETA here but should be read for prime-time shortly. The only strictly-local component of the work is calculating the public URLs from the TEI, so it should be broadly usable.

**Comment by PFSchaffner** [comment]
Sorry, Stuart, since I'm always interested in MARC-TEIHeader conversions, could you explain what this is about? Certainly in running conversions from MARC to TEI, as we do it, both MARC 505 and 520 translate into header fields, not body tags, but perhaps you are talking about a different situation? E.g. generating a 505 toc from the structure of the TEI text as tagged?

**Comment by stuartyeates** [comment]
My code assumes (a) you have a basic MARC record with an 856 to a public presentation of the document (b) you have the full TEI and (b) from the TEI you can calculate the 856.

My code is a metaprogram xsl  which takes the TEI and outputs a generated xsl file. 

The generated xsl files takes a MARCXML file, passing records through unchanged unless the 856 matches. If the 856 matches, the record (with the exception of matching 856s) is passed through, and the following things added (a) new 856s (in our case we're going from a single HTML 856 to ePub, HTML and PDF 856s), complete with the 'q' field (mime-type) and link text based on the full work name (b) 505 and 520 fields (c) 600, 610, 650, 700, 710 and 750 fields base don tei:name's in the header and body.

It is written to operate on very large TEI and MARCXML files. There are tune-able parameters to avoid running over the 99999 character hard limit on a MARC record (in theory this could be done automatically as a separate pass, but not something I've done yet). I am careful to avoid infringing on the human cataloging of core bibliographic content.

**Comment by PFSchaffner** [comment]
Thank you.

**Comment by kshawkin** [comment]
If the BPTL workgroup understands correctly, you are extracting useful data from the encoded body of the text to enhance the MARC records for these TEI documents by adding additional data to the MARC records.  But we are skeptical of a generic solution for processing bodies of texts. For example, would you want to extract _every_ persName in the document for an added entry on the catalog record?  So we are having trouble imagining generalizing this.  But we do like the idea of generating a TOC from the encoded text and think that this is worth recommending for [Thutmose II](http://wiki.tei-c.org/index.php/Thutmose_II) to include whenever it handles generation of MARC from TEI documents (currently under "plans for the future" at http://blackmesatech.com/2010/12/thutmose/userdoc.xml ).
