### ISSUE TITLE
Add (or update) examples to show use of modern authorities 

### ISSUE THREAD

**Issue by stuartyeates** [kshawkin/Best-Practices-for-TEI-in-Libraries#26]
Should include:
- https://http://viaf.org/viaf/137526058/
- http://orcid.org/0000-0003-3181-9310
- http://isni.org/isni/0000000119455417 
- some of the various http://id.loc.gov/ vocabularies
- https://en.wikipedia.org/ or https://www.wikidata.org/ URIs
- ...

**Comment by kshawkin** [comment]
See also related issue: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/5

**Comment by pcgorman** [comment]
http://www.geonames.org/2965402/

**Comment by kshawkin** [comment]
Elli agreed to take this on but welcomes collaboration.

**Comment by emylonas** [comment]
Prose to add to 3.8.3

provide alternative to the Shakespeare `@key` example using the LC linked data URL http://id.loc.gov/authorities/names/n78095332

why do we have the `@type="marc100"` ? 

and do we keep the GTN (Getty) ex? or should i just replace it with an `@ref` attribute instead, for ex. using the geonames example above? It wouldn't require glossing with a `<taxonomy>` or `<listPlace>`

**Comment by kshawkin** [comment]
During the BPTL call today, we realized that Elli was proposing revisions to vesion 3, not to the latest prose as already revised in implementing #5 .  She will review the latest version ( http://paramedic.wwp.northeastern.edu/~syd/temp/BPTL/main-driver.html#index.xml-body.1_div.3_div.9_div.3 ) and consider whether more illustrations here or elsewhere in the BPTL would be helpful.

**Comment by emylonas** [comment]
"Readily available software" ?? At least "software" or "simple tests can check"

"XSL and other software scripts can then check when encountering ref="#geo_0034" that xml:id="geo_0034" exists elsewhere in the document."

Also
"Just as the TEI Guidelines no longer recommend use of the key attribute, these Best Practices also recommend use of tag URIs in order to create unique local identifiers."

perhaps

"As in the TEI Guidelines (link here), these Best Practices recommend the use of the ref attribute with tag URIs as described in  RFC 4151 in order to create unique local identifiers that can also be shared across files and projects."

**Comment by emylonas** [comment]
Added a viaf link as well. 
I think it's ok. Perhaps slight edits as noted above.

**Comment by emylonas** [comment]
Is this a better link for RFC 4151?  [http://www.ietf.org/rfc/rfc4151](https://tools.ietf.org/html/rfc4151) rather than [http://www.ietf.org/rfc/rfc4151.txt](http://www.ietf.org/rfc/rfc4151.txt) which is what we (and the TEI) have now? @sydb @kshawkin

**Comment by emylonas** [comment]
Finished with d51b461

**Comment by kshawkin** [comment]
I don't see the difference between the two URLs for RFC 4151 that you pasted ...

**Comment by emylonas** [comment]
yes, there was no difference in the link text, but now that I fixed that, you'll see in comment above that one has `.txt` at the end, and the other doesn't. Latter takes you to a page that offers a variety of displays (`.txt`, `.html` and so on)

**Comment by kshawkin** [comment]
I see.  I suppose the one without ".txt" is better.  The search feature on the IETF website seems to treat that as the main version.

**Comment by emylonas** [comment]
closed with 7225038
