### ISSUE TITLE
ambiguity over use of <lb/>, <cb/>, and <pb/> in Level 4

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#31]
In BPTL 3.2.2. (Hyphenation), it says, "At Level 3, optionally distinguish uses of the hyphen with the `@break` and `@rend` attributes on `<lb>`, `<cb>`, and `<pb>` elements as appropriate. At Level 4, the use of the `@break` and `@rend` attributes on these elements [`<lb>`, `<cb>`, and `<pb>`] is mandatory.”  In fact, the description of Level 1 mentions `<pb/>` as one of two mechanisms for linking to page images, and the description of Level 3 mentions `<lb/>` and `<cb/>` as optional elements, so the use of these elements and the use of the `@break` and `@rend` attributes are both optional.

Level 4 is supposed to include all elements from Level 3 (plus others); however, we don't explain whether use of `<lb/>`, `<cb/>`, and `<pb/>` is mandatory at this level.  All we know is that if we use them, you are required to use `@break` and `@rend`.

We should specify whether use of `<lb/>`, `<cb/>`, and `<pb/>` is mandatory in Level 4.  I don't see any reason they should be mandatory, but I'm open to being convinced otherwise.

**Comment by pcgorman** [comment]
I don't think they should be mandatory, either - projects shouldn't be forced into doing a complete typographic transcription ('facsimile' in Menota terms) of the source. I also think we should only require @style/rend/rendition and @break when _all_ original hyphenation and line breaks are retained, as described in the hyphenation section, and not imply that they're required in all cases. This may have been the original intent, but the existing language makes a very broad statement.

**Comment by kshawkin** [comment]
This should probably be revised in conjunction with https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/21 .

**Comment by kshawkin** [comment]
During BPTL workgroup call today, @emylonas agreed to look at this while implementing #21 .

**Comment by emylonas** [comment]
I've changed the language in the hyphenation section #21 so that but there is no section specific to breaks. However, we don't say anywhere if these are required, and on what levels of BPTL. Likewise for line breaks and column breaks. What levels are these required on? Suggest changing the Page Break section to _Page,  Line and Column Breaks_ and then adding information on where/when these are required. It appears that page breaks are optional on Level 1, likely to appear but not required on Level 2 and might be required on Level 3, but it's not stated explicitly. 

Another way to handle this is to put ``<pb>, <lb>, <cb>`` in the tables of elements for each level when its usage changes.

**Comment by kshawkin** [comment]
During today's BPTL call, I pointed out that currently `<pb/>` is discussed in the element recommendations for Level 1, and `<lb/>` and `<cb/>` are discussed in the element recommendations for Level 3.  Elli said that she then thinks that everything is set with this issue and issue 21, but she asked Kevin to check over the changes that she committed.

**Comment by kshawkin** [comment]
For the record, when implementing this in https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/pull/49 , she followed @pcgorman 's suggestion that we would not require these milestone elements in Level 4 and has made this explicit in the prose.

**Comment by emylonas** [comment]
hopefully closed with commit 1bd07b5

**Comment by kshawkin** [comment]
Yes, we're all set here.
