### ISSUE TITLE
publicationStmt invalid

### ISSUE THREAD

**Issue by emylonas** [kshawkin/Best-Practices-for-TEI-in-Libraries#40]
`<publicationStmt>` is invalid, because it only contains one element `<availability>`. `<publicationStmt>` can either be unstructured, and contain an `<ab>` or `<p>` with free text content, or it has to have one of the following as the initial element: `<publisher>, <distributor>, <authority>`. 

I suggest that we use `<authority>Text Encoding Initiative in Libraries SIG</authority>` or just `<authority>Text Encoding Initiative</authority>` since this is supposed to show who is making the text available.

**Comment by emylonas** [comment]
If we can reach consensus on this, I can commit my changes, otherwise the file remains invalid. (I can just put an empty `<authority>` in as well, and we can quibble over wording later.)

**Comment by kshawkin** [comment]
It sounds like you've found an error in one of the ODD files themselves rather than an error in the content model of `<publicationStmt>` as specified in `lib-header.odd` or an incorrect statement in the prose in one of the ODD files.  However, I can't find the problem.  Can you give me a filename and line number?

**Comment by emylonas** [comment]
I'm getting an error in main-driver.odd line 31 - inside `<publicationStmt>`. 

Yes, it is an error in the file - it's not an error in the content model, but an inconvenience that I've noticed before (and others have as well).

**Comment by kshawkin** [comment]
Ah yes, I see now.  I would just add `<authority>TEI SIG on Libraries</authority>` as found in the other ODD files.  Thanks!

**Comment by emylonas** [comment]
closed with commit 94e9705 merged
