### ISSUE TITLE
header section: note about complete customizations

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#43]
lib-header.odd contains the following:

> `<p>Note that this is not a complete customization. It is
>           just one specification group that is used by each of the
>           customizations for levels 1–4.</p>`

I think this should be turned into an XML comment since, in the HTML version of the full BPTL (when the ODD files are joined together, this paragraph appears in the middle, out of context.

**Comment by sydb** [comment]
Yup. Good idea. (Either a comment, a PI, or a lot of explanatory prose is needed.)

**Comment by sydb** [comment]
I addressed this in mid-December, but because I had broken other things at the same time did not push it until 5 days ago, and forgot to close the ticket.
Fixed in c3fb2b9bec18c0e9b4f037908f7f1bdc2ff525a6.
