### ISSUE TITLE
controlled vocabulary for @type on divs?

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#45]
We should consider whether to prescribe a controlled vocabulary of values for `@type` aside from "section" (which we mention).  Note that P5 gives some values for divs that occur in front and back matter: see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSFRONT and http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSBACK .  We could refer to these, though we might also want values for things that appear between front and back matter.

**Comment by kshawkin** [comment]
Or maybe don't bother, assuming people will follow our general documentation on values of `@type`: http://www.tei-c.org/SIG/Libraries/teiinlibraries/main-driver.html#index.xml-body.1_div.3_div.8_div.1

**Comment by emylonas** [comment]
Agreed, best to keep it simple.

**Comment by emylonas** [comment]
In meeting 11/13 suggestion that we take front matter and back matter list of `@type` from Guidlines and and merge with WWP list of `@type` for `<div>` and clean up the resulting list. This should be a suggested list of values in the ODD and prose recommends modification for each project.

**Comment by sydb** [comment]
The list from the WWP is as follows. Note that many of the descriptions are written by yours truly, and thus may be suboptimal. (If you see a good one it’s probably by Julia or Sarah.:-)

``` xml
  <valItem ident="act">
    <desc>An act in a dramatic text.</desc>
  </valItem>
  <valItem ident="advert">
    <desc>An advertisement for a printed work or other product.</desc>
  </valItem>
  <valItem ident="argument">
    <desc>A short passage at the start of a document or section giving a prose description of its contents.</desc>
  </valItem>
  <valItem ident="book">
    <desc>A major structural component of a long work, identified explicitly in the text as a <soCalled>book</soCalled>.</desc>
  </valItem>
  <valItem ident="calendar">
    <desc>A formal calendar; a document or document section identifying itself as a calendar</desc>
  </valItem>
  <valItem ident="castlist">
    <desc>A list of characters in a dramatic text</desc>
  </valItem>
  <valItem ident="chapter">
    <desc>A chapter, typically in a prose document </desc>
  </valItem>
  <valItem ident="colophon">
    <desc>A short inscription, typically at the end of a book or manuscript, containing the title, printer, date and place of printing, etc.</desc>
  </valItem>
  <valItem ident="concluding">
    <desc>Any section of the back matter that does not carry a more specific designation; includes afterwords, epilogues, codas, etc.</desc>
  </valItem>
  <valItem ident="confession">
    <desc>A section that is identified explicitly as a <soCalled>confession</soCalled> in a text that uses this as a main structural division.</desc>
  </valItem>
  <valItem ident="contents">
    <desc>A table of contents.</desc>
  </valItem>
  <valItem ident="corrigenda">
    <desc>A section describing corrections to be made to the document.</desc>
  </valItem>
  <valItem ident="drama">
    <desc>A dramatic text.</desc>
  </valItem>
  <valItem ident="dramaPart">
    <desc>A portion of a drama other than a prologue, act, scene, or epilogue.</desc>
  </valItem>
  <valItem ident="ded">
    <desc>A dedication.</desc>
  </valItem>
  <valItem ident="docAuthorization">
    <desc>A statement indicating that the document's printing was officially authorized.</desc>
  </valItem>
  <valItem ident="endnotes">
    <desc>A section containing endnotes for the document.</desc>
  </valItem>
  <valItem ident="entry">
    <desc>An entry in a document that is organized as a log or diary with dated entries.</desc>
  </valItem>
  <valItem ident="epigraph">
    <desc>A short quotation at the start of a document or section, often accompanied by an attribution.</desc>
  </valItem>
  <valItem ident="epilogue">
    <desc>A short concluding section, usually of a dramatic or fictional work.</desc>
  </valItem>
  <valItem ident="essay">
    <desc>A short prose non-fiction document.</desc>
  </valItem>
  <valItem ident="examination">
    <desc>A section that is identified explicitly as an <soCalled>examination</soCalled> in a text that uses this as a main structural division.</desc>
  </valItem>
  <valItem ident="frontispiece">
    <desc>A portrait or other image (usually of the author, usually full page) printed at the front of a document. </desc>
  </valItem>
  <valItem ident="index">
    <desc>An alphabetical listing of the topics in a document, usually with accompanying page references</desc>
  </valItem>
  <valItem ident="imprimatur">
    <desc>A formal indication (usually on the title page or in the front matter) that the document has received official license to be printed.</desc>
  </valItem>
  <valItem ident="letter">
    <desc>Any document in epistolary form, i.e. addressed by a sender to a recipient.</desc>
  </valItem>
  <valItem ident="meditation">
    <desc>A section that is described explicitly as a <soCalled>meditation</soCalled> in a document that uses this as a main structural division.</desc>
  </valItem>
  <valItem ident="narrative">
    <desc>An embedded narrative.</desc>
  </valItem>
  <valItem ident="nonfictionProse">
    <desc>A text intended to be nonfiction consisting primarily of prose.</desc>
  </valItem>
  <valItem ident="novelPart">
    <desc>A portion of a novel.</desc>
  </valItem>
  <valItem ident="part">
    <desc>A major component of a work, containing further subdivisions.</desc>
  </valItem>
  <valItem ident="petition">
    <desc>A formal plea to an authority.</desc>
  </valItem>
  <valItem ident="placeholder">
    <desc> </desc>
  </valItem>
  <valItem ident="poem">
    <desc>A poem.</desc>
  </valItem>
  <valItem ident="poemGroup">
    <desc>A group of two or more poems under a common heading.</desc>
  </valItem>
  <valItem ident="prayer">
    <desc>A prayer.</desc>
  </valItem>
  <valItem ident="prefatory">
    <desc>A section of the front matter that does not carry a more specific designation.</desc>
  </valItem>
  <valItem ident="prologue">
    <desc>An opening section of a literary work (typically drama or poetry). </desc>
  </valItem>
  <valItem ident="recipe">
    <desc>A recipe in a cookbook.</desc>
  </valItem>
  <valItem ident="scene">
    <desc>A scene in a dramatic text </desc>
  </valItem>
  <valItem ident="section">
    <desc>A generic section of a larger work.</desc>
  </valItem>
  <valItem ident="speech">
    <desc>A section described as a speech or public lecture, in a document that uses this as a main structural division.</desc>
  </valItem>
  <valItem ident="subsection">
    <desc>A generic subdivision of a section.</desc>
  </valItem>
  <valItem ident="timeline">
    <desc>A timeline. </desc>
  </valItem>
  <valItem ident="tract">
    <desc>A short treatise in pamphlet form often on a religious subject.</desc>
  </valItem>
  <valItem ident="undetermined">
    <desc>A text component whose genre has not been determined. </desc>
  </valItem>
  <valItem ident="volume">
    <desc>A single printed volume in a multi-volume work. </desc>
  </valItem>
```

**Comment by emylonas** [comment]
The following are the values from the TEI:

**Front Matter** 
- preface (WWP has _prefatory_)
- ack
- dedication (WWP has _ded_)
- abstract
- contents (also in WWP)
- frontispiece (also in WWP)

**Back matter**
- appendix
- glossary
- notes
- bibliogr
- index (also in WWP)
- colophon (also in WWP)

This is the WWP list for div types in the body of a text, Suggest keeping the ones in the first list as they are either indicating parts of the book process, and suggest leaving out the more genre specific ones, allowing people to use them as they wish. I think we should keep the first set of values, possibly the second and am ambivalent about the third.

**Keep-Structural components**
_book_ - A major structural component of a long work, identified explicitly in the text as a "book".
_chapter_ - A chapter, typically in a prose document 
_part_ - A major component of a work, containing further subdivisions.
_section_ - A generic section of a larger work.
_subsection_ - A generic subdivision of a section.
_volume_ - A single printed volume in a multi-volume work.
 _endnotes_ - A section containing endnotes for the document.

**Book Business**
_advert_ - An advertisement for a printed work or other product.
 _corrigenda_ - A section describing corrections to be made to the document.
_docAuthorization_ - A statement indicating that the document's printing was officially authorized.
 _imprimatur_ - A formal indication (usually on the title page or in the front matter) that the document has received official license to be printed.

**Divs that might have specialized structures**
 _drama_ - A dramatic text.
 _dramaPart_ - A portion of a drama other than a prologue, act, scene, or epilogue.
_act_ - An act in a dramatic text.
 _scene_ - A scene in a dramatic text 
 _castlist_ - A list of characters in a dramatic text
 _poem_ - A poem.
 _poemGroup_ - A group of two or more poems under a common heading.
_argument_ - A short passage at the start of a document or section giving a prose description of its contents.
  _entry_ - An entry in a document that is organized as a log or diary with dated entries.
_concluding_ - Any section of the back matter that does not carry a more specific designation; includes afterwords, epilogues, codas, etc.
 _epigraph_ - A short quotation at the start of a document or section, often accompanied by an attribution.
 _prologue_ - An opening section of a literary work (typically drama or poetry). 
 _epilogue_ - A short concluding section, usually of a dramatic or fictional work.
 _narrative_ - An embedded narrative.
 _nonfictionProse_ - A text intended to be nonfiction consisting primarily of prose.
 _novelPart_ - A portion of a novel.
  
The following are some more genre-based values, we might leave them up to the encoders or suggest them in a "for instance" list. Perhaps listed in encodingDecl? 

calendar, confession, essay,  timeline, examination, letter, petition, prayer, recipe, speech, tract, pamphlet, meditation

**Comment by sydb** [comment]
Conference call (@sydb, @emylonas, @kshawkin) agrees to use Elli’s list of 2016-12-12 as a `type=semi` list except: confession, petition, tract, pamphlet, meditation; and to change `bibliogr` to `bibliography` and to add `foreword`.

Also repeat lists in the prose, and  make comments in ODD and prose pointing out that any changes need to be noted in both.

This applies to Levels 2, 3, & 4

**Comment by emylonas** [comment]
In the processing of creating the list, I wonder if we want to make abbreviations for the types or just leave them as full words. I will add in `valItem/gloss` information about the ones that are likely to belong in front or back matter.

**Comment by kshawkin** [comment]
During the BPTL call on 2017-02-13, we reaffirmed our decision on Jan. 9 to keep the attribute values as full words.

**Comment by emylonas** [comment]
@kshawkin as I rewrite the EncodingDesc table to include information on the SchemaRef element, I am moving the MARC equivalent information:
<item>856 $z, which includes boilerplate text depending on encoding level and how the TEI document is presented to the user (as page images, text, or both)</item>
into the schemaRef line. Is the MARC information still correct.

**Comment by kshawkin** [comment]
I've merged https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/pull/54 and then improved the XML comment meant to remind us to keep everything in sync.  However, I realize now that we've only revised the attDef for `<div>` but not for numbered div elements as well.  Elli, could you make the necessary changes for that?

**Comment by emylonas** [comment]
ok will do

**Comment by emylonas** [comment]
I think this should be a class, if it's going to apply to several elements. @sydb where should I put the definition? then `<div>` and numbered divs can be members.

**Comment by sydb** [comment]
During BPTL call, we suggested a new class `att.BTPL.div.typed` to be put in lib-header.odd. (Yes, we’re mis-using lib-header.odd as a lib-common.odd, but that builds on our current somewhat lax practice.)

**Comment by emylonas** [comment]
Level3.odd referenced model.divXlike in the element spec for each of the numbered divs. level4.odd did not. Removing them from level3.odd seems to have had no ill effects, so they are gone. Made class as above, referencing it from all appropriate div element specs. 
Closing with efb53f3
