### ISSUE TITLE
BPTL Level 4 and TEI simplePrint

### ISSUE THREAD

**Issue by emylonas** [kshawkin/Best-Practices-for-TEI-in-Libraries#46]
Reconcile [TEI Simple](https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_simple.odd) and Level 4 and approach Council if we want to suggest changes in Simple or just make changes to BPTL level 4. New issue arising out of #23

**Comment by kshawkin** [comment]
We could also consider the [DTA Base Format](http://www.deutschestextarchiv.de/doku/basisformat_en), which Martin Mueller says is slightly tighter than TEI Simple.

**Comment by kshawkin** [comment]
During the BPTL call on 2017-04-03, we decided that TEI simplePrint is actually closer to Level 5.  We agreed to edit the description of Level 5 to say that if contemplating Level 5, you should consider whether TEI simplePrint is appropriate for your type of document(s).

I will implement.

**Comment by kshawkin** [comment]
Done at https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/45d9f018517dc99d525968f92720ac1a9e481bb6 .
