### ISSUE TITLE
rewrite discussion of @key and @ref to discuss magic tokens and Linked Data

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#5]
The TEI Guidelines no longer recommend use of @key (though it has not been officially deprecated).  For things where you used to use @key, you should now either:

a) Use a "tag" URI scheme (as described in RFC 4151) on @ref: see implementation at https://github.com/TEIC/TEI/issues/337 .

b) Use a private URI scheme on @ref as described at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SAPU .

In the BP, the example with Shakespeare is no longer a good example of a need for a "key-like" ("magic token") attribute value since the Library of Congress now provides URIs for their authority records on id.loc.gov.  So we should discuss how to link to Linked Data (whether in this section or elsewhere in the document), and this section should instead include a better example for where you'd need a "key-like" attribute value.

**Comment by sydb** [comment]
I agree completely. (Although we should not use the phrase “key-like” IMHO.)

**Comment by kshawkin** [comment]
See also related issue: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/26

**Comment by pcgorman** [comment]
+1

**Comment by kshawkin** [comment]
During today's monthly call, I suggested that we postpone a decision until we get Council to consider whether P5 should really offer both (a) and (b).  Right now (a)—tag URIs—is discussed at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONARS and in the specification for `att.canonical` (which includes `@key`), whereas (b)—private URIs—is discussed at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SAPU and elsewhere. I will create a new issue at https://github.com/TEIC/TEI/issues asking that this be considered.

**Comment by kshawkin** [comment]
In retracing the history of the introduction of tag URIs and private URI schemes into P5, it seems that the Council included both on purpose.  See discussion at http://wiki.tei-c.org/index.php/Prefix_Definition_Proposal , especially the footnote at the bottom of that page.  So I won't create a new issue for the Council to consider.

The BPTL group should decide whether to recommend just one of these for the BPTL or instead discuss both of them as options.

**Comment by kshawkin** [comment]
The BPTL workgroup decided to remove recommendations for `@key` and instead recommend use of tag URIs.  However, we will also note that people are welcome to define a private URI scheme in their encoding as explained at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SAPU .  We'll note that this can be helpful for shortening tag URIs (which can become cumbersome).

I will draft some prose for the BPTL to address this and post in this ticket.

**Comment by kshawkin** [comment]
Note that [Martin Holmes's recent post to TEI-L](https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;41ee9356.1606) may be useful in drafting the prose.

**Comment by kshawkin** [comment]
If I were more experienced with GitHub and didn't see Council members struggle with it all the time, I would create a branch and create revisions there.  Instead, I will post my draft revisions here.

I propose replacing [section 3.8.3 ("key and ref")](http://www.tei-c.org/SIG/Libraries/teiinlibraries/main-driver.html#index.xml-body.1_div.3_div.8_div.3) with the following:

<details>

```
<div type="====">
          <head>ref and tag URIs</head>
          <p>The <att>ref</att> attribute is available on a variety of elements, including <gi>persName</gi>, <gi>orgName</gi>
          <gi>author</gi>, and <gi>title</gi>. Its value is a URI that identifies external metadata about the content of the
          element. Linked Data applications in libraries have led to many authority records being made accessible through URIs, 
          allowing this attribute to be used for disambiguation. For example:
          </p>
          <egXML xmlns="http://www.tei-c.org/ns/Examples">
            <placeName ref="http://vocab.getty.edu/page/tgn/7012924">Indianapolis</placeName>
          </egXML>

          <p>Still, there are times when an outside URI for disambiguation is not available. An encoding project could use URI 
          fragment identifiers (see above) to point to an authority record (identified with <att>xml:id</att>) within the same 
          TEI document. For example, in the transcription of the text, you can use
          <egXML xmlns="http://www.tei-c.org/ns/Examples">
            <placeName ref="#geo_0034">Texas</placeName>
          </egXML>
          which would be defined in a controlled vocabulary elsewhere:
          <egXML xmlns="http://www.tei-c.org/ns/Examples">
            <listPlace>
              <place xml:id="geo_0034">
                <placeName>
                  <settlement type="village">Texas</settlement>
                  <region type="state">Maryland</region>
                </placeName>
              </place>
            </listPlace>
          </egXML>
          </p>
          <p>Readily available software can then check when it
          encounters <code>ref="#geo_0034"</code> that
          <code>xml:id="geo_0034"</code> exists elsewhere in the
          document.</p>

          <p>If there is a desire to have an authority file spanning documents, it might be tempting 
          to use relative URIs (as discussed above), rather than an absolute URIs, in the value of <att>ref</att> in order to 
          create a local authority file.  However, such URIs cannot be resolved in a stable way as the location of the TEI document 
          changes. Just as the TEI Guidelines <ref target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONARS">no 
          longer recommend use of the <att>key</att> attribute</ref>, these <title>Best Practices</title> also recommend use of 
          <term>tag URIs</term> in order to create unique local identifiers. For example, a tag URI created in 2016 for 
          nabokovpapers.org might look like this:
          <egXML xmlns="http://www.tei-c.org/ns/Examples">
            <persName ref="tag:nabokovpapers.org,2016:B_V001">Blavdak Vinomori</persName>
          </egXML>
          If desired, such tag URIs could be shortened by creating a private URI scheme 
          <ref target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SAPU">as described in the TEI Guidelines.</p>

        </div>
```

</details>

I would also replace examples elsewhere in the BPTL that use `@key` with new ones following what I've just written above.

**Comment by kshawkin** [comment]
During today's BPTL call, @PFSchaffner agreed to read my proposed revisions to the prose.

**Comment by kshawkin** [comment]
During today's BPTL call, @PFSchaffner said that he had reviewed the revisions and that everything made sense.  No one else was interested in reviewing, so I will commit this change (soon, once I have some more time).
