### ISSUE TITLE
update BPTL ODDs to use Pure ODD syntax

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#50]
Syd suggested that we do this even though he admitted that there's no danger of deprecation of "impure" ODDs anytime soon.  He said the update can be done programmatically.  He volunteered to take this on, but Kevin suggested waiting till near the end so that we don't introduce any impure ODD syntax while implementing other tickets after this one.

**Comment by sydb** [comment]
Implemented for lib-header.odd while I was working on other tickets. Pushed at dffbeb5ca583ec69c53158d8671e92ffac74683c

**Comment by sydb** [comment]
Implemented for levelN.odd at 939b9f537c193d1405f19ebf7b79592bfffea23e.
