### ISSUE TITLE
Appendix A: Recommended Attributes

### ISSUE THREAD

**Issue by emylonas** [kshawkin/Best-Practices-for-TEI-in-Libraries#51]
This Appendix contains a list of attributes, but they are 
a) not linked to the elements on which they appear
b) don't explain which ones are mentioned in the BP document and which are "favorites" 

Either get rid of the list, or make it more useful.

**Comment by kshawkin** [comment]
For the record, I did some digital archeology and see that the last workgroup revising the BPTL had decided to create a list of all attributes that can be used within `<text>`: see [the original question](http://wiki.tei-c.org/index.php?title=Talk:Best_Practices_for_TEI_in_Libraries&oldid=7569#Pending_Review:_Use_of_any_P5_attributes), [item number 2 in the minutes of the June 2, 2010 meeting](http://wiki.tei-c.org/index.php/Minutes_from_June_2,_2010), and [our notes tracking what happened](http://wiki.tei-c.org/index.php?title=Talk:Best_Practices_for_TEI_in_Libraries&oldid=8070).  (However, Appendix A does not currently mention this constraint, and I'm not sure whether the list we included is actually limited that way.)  As you can see, the thinking was that if someone sat down to encode and followed the BPTL, we give guidance on using elements but don't address use of the many attributes that come with these elements as defined in P5.  However, Syd later created ODDs that attempted to remove anything not mentioned in the BPTL, so maybe this is no longer necessary.

**Comment by emylonas** [comment]
Agreed during BPTL call on 2017-03-06 to remove it. make sure there are not references to this appendix in the prose

**Comment by emylonas** [comment]
closed with  e519b72
