### ISSUE TITLE
reconsider our use of modal expressions

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#52]
The introduction to the BPTL says:

> As guidelines rather than a specification, these _Best Practices_ use _should_ instead of _must_ in nearly all cases (except where a practice is required by P5), with optional practices indicated by _may_. However, to encourage conformance to these _Best Practices_, the ODD files will generate schemas that _require_ use of recommended elements (indicated by _should_).

However, the "big header table" in fact uses "required" quite frequently.  Perhaps this is actually clearer to people.

Consider following practices discussed at https://github.com/TEIC/TEI/issues/1175 .

**Comment by kshawkin** [comment]
During BPTL call on 2017-04-03, we agreed that we will at least need to use "must" or a similar obligatory expression for cases where an attribute, if used, must have a value.  I agreed to think through this issue and propose something to the group.

**Comment by kshawkin** [comment]
To review: While the TEI Guidelines are "guidelines" (which sounds like nothing is mandatory), P5 generally uses "must" for situations that are mandated by the schema.  On the other hand, while the BPTL document is "best practices" (which also sounds like nothing is mandatory), version 3.0 of the BPTL takes a different approach but is inconsistent, as explained above in the original issue.

I propose that we use "must" only when something is mandated in P5.  Here are two examples:

a) `<head>` cannot follow an `<p>`s within a div.

b) If a certain attribute is used, it must have a value.

In other cases, we will continue using "should".

Therefore, I propose to do the following:

1. Copyedit the text in the introduction as follows:

> As guidelines rather than a specification, these _Best Practices_ use _should_ or _recommended_ instead of _must_ to give recommendations in all cases except where a practice is required by P5.  Optional practices are indicated by _may_ or _optional_. However, to encourage conformance to these _Best Practices_, the ODD files will generate schemas that _require_ even use of recommended elements (those indicated by _should_ or _recommended_).

2. In Level 2, change

> As in the TEI, this element must be the first child of a `<div>` or `<div1>`.

to:

> As in the TEI Guidelines, this element must appear before the `<ab>` for that division.

3. In "Element Recommendations for Level 4", remove the row for `<head>` since the statement about the first child is technically inaccurate and any revision to make it accurate would state the obvious.

4. Search elsewhere for use of "must" and "required" and check whether the practice described is actually required by P5.  If not, change to "recommended".

**Comment by kshawkin** [comment]
During the BPTL call today, Syd and Elli agreed to review my proposal in the previous comment.  If they approve, I will implement.

**Comment by emylonas** [comment]
one slight word-smithing change to the introduction text:
it says
`the ODD files will generate schemas that require even use of recommended elements `
change to
` the ODD files will generate schemas that also require the use of recommended elements`
or 
` the ODD files will generate schemas that require the use of recommended elements`
that `even` was confusing me.

**Comment by sydb** [comment]
I think the proposal is fine, and (in general) we should go with it. I think Elli is right that the last sentence deserves word-smithing, but would be even more blunt:
> the ODD files describe schemas that *require* recommended practices (those indicated herein by “should” or “recommended”) in addition to practices required by TEI P5.

or some such.

**Comment by kshawkin** [comment]
Revised proposal ...

1. Copyedit the text in the introduction as follows:

> As guidelines rather than a specification, these _Best Practices_ use _should_ or _recommended_ instead of _must_ to give recommendations in all cases except where a practice is required by P5.  Optional practices are indicated by _may_ or _optional_. However, to encourage conformance to these _Best Practices_, the ODD files describe schemas that _require_ recommended practices (those indicated herein by _should_ or _recommended_) in addition to practices required by TEI P5.

2. In Level 2, change

> As in the TEI, this element must be the first child of a `<div>` or `<div1>`.

to:

> As in the TEI Guidelines, this element must appear before the `<ab>` for that division.

3. In "Element Recommendations for Level 4", remove the row for `<head>` since the statement about the first child is technically inaccurate and any revision to make it accurate would state the obvious.

4. Search elsewhere for use of "must" and "required" and check whether the practice described is actually required by P5.  If not, change to "recommended".

I will implement.

**Comment by kshawkin** [comment]
Postponing to make sure that my sweep of modal expressions doesn't miss any other late changes.

**Comment by kshawkin** [comment]
During BPTL call, Elli agreed to work on prose for step 4.  Syd may help out examining Schematron rules that also use "must" or "required" to check them as well.

**Comment by sydb** [comment]
Elements that contain “must” or “required”, excluding those in `<egXML>`:

~~~~~xml

---------lib1.odd: **OK**
<p>For technical reasons, the TEI namespace is not
                displayed in examples. However, a TEI namespace
                declaration is required. It is typically given once on
                the TEI root element, e.g. <tag type="start">TEI
               </tag>.</p>

This 
---------lib1.odd:  **OK**
<p>This element is required. The TEI namespace should
                be specified on this element, e.g. <tag type="start">TEI
               </tag>.</p>


---------lib2.odd: **OK**
<cell>Recommended if headings are present. As in the TEI Guidelines, this element must appear before the <gi>ab</gi> for that division.</cell>


---------lib2.odd:  **OK**
<p>This element is required. The TEI namespace should
                be specified on this element, e.g. <tag type="start">TEI
               </tag>.</p>


---------lib3.odd: **OK**
<p>This element is required. The TEI namespace should
                be specified on this element, e.g. <tag type="start">TEI
               </tag>.</p>


---------lib4.odd: **GUIDELINES SAY: "The list element should be used to mark its structure." Changed to "should"** 
<item>must use a <gi>list</gi> with <gi>item</gi>s. For an
              index, use <tag>ref target="____"</tag> to mark up page
              numbers given in the index, with the value of
              <att>target</att> referring to the <att>xml:id</att>
              attribute of the <gi>pb</gi> of the referenced page.
              </item>


---------lib4.odd: **OK**
<p>This element is required. The TEI namespace should
              be specified on this element, e.g. <tag type="start">TEI
             </tag>.</p>

---------lib-header.odd: **NOT RELEVANT**
<p>Each institution and even each project may have a
	  different approach to the way electronic texts are created
	  in TEI and then represented in a larger public catalog
	  through MARC bibliographic records. At one institution, the
	  same unit (e.g., a cataloging department) may be responsible
	  for creating both TEI headers and MARC bibliographic
	  records, while at other institutions the work may be
	  distributed among different units. Within the library
	  domain, metadata or cataloging experts are usually required
	  for at least review and standardization of both the TEI
	  header and the MARC bibliographic record.</p>


---------lib-header.odd:  **not in TEI GUIDELINES FIXED**
<s:assert test="@when">Dates inside the
		  publication statement must have @when
		  (and should not have content)</s:assert>


---------lib-header.odd:  **not in TEI GUIDELINES FIXED**
<s:report test="string-length(       normalize-space(.) ) &gt; 0">Dates
		  inside the publication statement should
		  not have content (and must have
		  @when)</s:report>


---------lib-header.odd: **DOES NOT APPEAR TO BE REQUIRED BY GUIDELINES** DID SOME REWORDING OF THE SCHEMATRON RULE --DONE
<s:assert test="/tei:TEI/tei:teiHeader/tei:encodingDesc/tei:tagsDecl/tei:namespace/tei:tagUsage/@gi">
			The use of divisions (i.e., whether numbered or
			unnumbered divisions are used) must be
			documented in a &lt;tagUsage&gt; element (inside a
		      &lt;namespace&gt; element ... </s:assert>

The next 4 are all "should" because guidelines say "should not contradict"
---------lib-header.odd:
<s:assert test="@level='s'">When a child of
		      &lt;seriesStmt&gt;, the level of a title must be
		      specified as 's'.</s:assert>


---------lib-header.odd:
<s:assert test="@level='s'">When inside the
		      series-level portion of a structured bibliographic
		      citation, the level of a title must be specified
		      as 's'.</s:assert>


---------lib-header.odd:
<s:assert test="@level='a'">When a child of
		      &lt;analytic&gt;, the level of a title must be
		      specified as 'a'.</s:assert>


---------lib-header.odd:
<s:report test="@level='a'">When a child of
		      &lt;monogr&gt;, the level of a title must not be
		      specified as 'a'.</s:report>
~~~~~

**Comment by emylonas** [comment]
closing with 5315d08
