### ISSUE TITLE
transcriptional omissions

### ISSUE THREAD

**Issue by sydb** [kshawkin/Best-Practices-for-TEI-in-Libraries#53]
The prose in 3.2 “Transcription” is confusing. (Ambiguous as to whether last sentence applies only to level 4 or all levels.) But moreover, why not suggest use of `<samplingDecl>`? Does it’s history as coming from the corpus linguistic community taint it?

**Comment by kshawkin** [comment]
I agree that we need to clarify which level(s) the last sentence applies to.  I suggest saying that it applies to all levels.

As for use of `<samplingDecl>`, I recall that we felt that this was meant only for linguistic sampling, but I see now that http://www.tei-c.org/release/doc/tei-p5-doc/en/html/HD.html#HD52 contains a fine example that is not at all linguistic.  So you're probably right that this should be revised, both here and in the table of header elements.

**Comment by emylonas** [comment]
Revise wording so as to recommend `<samplingDecl>`, make changes in table and ODDs. Only allow `<p>` in `<samplingDecl>` if other header elements are similarly constrained.

**Comment by sydb** [comment]
Partially address in 7093f9c: I added `<samplingDecl>` to the table and schema, but I did not get a chance to change the prose.

**Comment by kshawkin** [comment]
During the BPTL call on 2017-04-03, Andrew agreed to finish the prose changes.

**Comment by arouner** [comment]
I am not sure this was all that was needing to be changed, but I changed just one paragraph to:

at Level 4 and above, the transcription in most cases would be complete. Any omissions of material found in the original work (at any encoding level) should be noted in the <samplingDecl> in the TEI header (departing from the previous version of the best practices which recommended omissions be noted in the <editorialDecl>.)

**Comment by arouner** [comment]
at Level 4 and above, the transcription in most cases would be complete. Any omissions of material found in the original work (at any encoding level) should be noted in the <samplingDecl> in the TEI header (departing from the previous version of the best practices which recommended omissions be noted in the <editorialDecl>.)

**Comment by arouner** [comment]
I did not attempt to branch/commit etc.  Should lib-header.odd also be changed where it says "<item>notes about omissions of material found in the original work</item>" under <tag>editorialDecl</tag>?

**Comment by arouner** [comment]
I qualified "at Level 4 and above, the transcription should be complete" with "in most cases" imagining that there might be a project which needed relatively sophisticated encoding but which did not include all of a given original text--I certainly could have misinterpreted the encoding level here.

**Comment by kshawkin** [comment]
During the BPTL call on 2017-05-08, we agreed that Syd would finish the work on this issue.

**Comment by sydb** [comment]
I **think** (but am not sure) that between us, Andrew & I have caught all the bits that need to be updated. Last tweak on this was to actually change 3.3 Transcription (which used to be 3.2, I guess). Done at 3651767.
