### ISSUE TITLE
consider <p> and <ab> inside of header elements

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#56]
TEI P5 has various header elements that contain prose description -- for example, `<availability>`.  P5 allows you to use either `<p>` or `<ab>`, but at in [the big table of header elements](http://www.tei-c.org/SIG/Libraries/teiinlibraries/main-driver.html#index.xml-body.1_div.4_div.1_div.6), we only mention `<p>`.  We should:

1. Consider whether to allow `<ab>` as well, advising the user to use whichever is appropriate depending on whether the contained prose contains one or more complete sentences.
2. Depending on the outcome, verify that the schema allows only `<p>` or allows both.

**Comment by kshawkin** [comment]
We agreed to allow only `<p>` inside the header.  Syd will make schema change (perhaps add Schematron rule) to make this happen.

**Comment by sydb** [comment]
Done (at 91f5f3f):

1. Updated version # to 3.2.0a
2. Added Schematron rule that complains about `<ab>` inside `<teiHeader>`

Did NOT test yet.
