### ISSUE TITLE
revisit encoding of ISBNs

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#6]
We recommend two values of @type on `<idno>`, but since then, the Guidelines standardized on `<idno type="ISBN">` (where previously there were some examples of `<idno type="isbn">`).  Perhaps we should standardize on `<idno type="ISBN">` as well and leave it to users to determine whether the value given is a 10-digit or 13-digit ISBN.  After all, they will already have to do some processing to add or remove hyphens within the ISBN (since use with regard to this varies).

**Comment by sydb** [comment]
if ( string-length( translate( $isbn,'- ','') ) eq 13) then 'ISBN13'
else if (string-length( translate( $isbn,'- ','') ) eq 10) then 'ISBN10'
else 'idunno'
[untested :-) ]

**Comment by stuartyeates** [comment]
ISBNs have a check digit. This allows us to identify ISBNs even without a type, right? And conversely throw an exception when it doesn't match and should

**Comment by kshawkin** [comment]
During workgroup call today, we decided to update the recommended values of `idno@type`, removing both `isbn-10` and `isbn-13` and replacing with `ISBN` in:
- the big table of header values
- in any `elementSpec`s
- in any examples

I will implement after Feb. 8 unless objections or further discussion occurs here.
