### ISSUE TITLE
breaks broken

### ISSUE THREAD

**Issue by sydb** [kshawkin/Best-Practices-for-TEI-in-Libraries#60]
The `att.breaking` elements are:
 * `<cb>` = column begin
 * `<gb>` = gathering begin
 * `<lb>` = line begin
 * `<pb>` = page begin
 * `<milestone unit="somethingElse">` = boundary between somethings else

We allow:

schema | cb | gb | lb | pb | milestone
----------|----|----|----|----|--------
level 1 |    | gb |    | pb |
level 2 |    | gb |    | pb |
level 3 | cb | gb | lb | pb |
level 4 |    | gb | lb | pb |

Surely this can’t be correct. I’m guessing we want `<cb>` included at level 4, and `<gb>` included either in none or only at level 4.

**Comment by kshawkin** [comment]
Agree that `cb` needs to be in Level 4.  As for `gb`, we haven't discussed that element anywhere, and my sense is that it's so specialized that we'd consider that to be Level 5 encoding (and thus we don't need to add it to anything).

**Comment by emylonas** [comment]
agree -- `<cb>` and `<lb>` in levels 3, 4, `<gb>` removed completely

**Comment by sydb** [comment]
Fixed at 10f6eb2. We now allow:

schema  | cb | gb | lb | pb | milestone
--------|----|----|----|----|--------
level 1 |    |    |    | pb |
level 2 |    |    |    | pb |
level 3 | cb |    | lb | pb |
level 4 | cb |    | lb | pb |
