### ISSUE TITLE
3.8. Linking Between Encoded Text and Images of Source Documents

### ISSUE THREAD

**Issue by kiyonoriNagasaki** [kshawkin/Best-Practices-for-TEI-in-Libraries#62]
Dear all,

Thank you very much for the tremendous work. I would like to adopt it in various cases.

By the way, regarding mention of IIIF in "3.8. Linking Between Encoded Text and Images of Source Documents", while IIIF specifications will be updated soon from 2.x to 3.x, I would like to suggest to include a sentence like following in the middle of the paragraph treating IIIF:

A facs attribute can be linked with a URL of full size image of IIIF Image API.

**Comment by sydb** [comment]
Makes sense to me and @emylonas. How about having the last para of [3.8](http://www.tei-c.org/SIG/Libraries/teiinlibraries/3.1.0a/main-driver.html#txtimglnk) read

> The International Image Interoperability Framework (IIIF), with its growing user community, is likely to emerge as an alternative mechanism for linking between encoded text and images of source documents. The value of a `@facs` attribute can be a IIIF API URL (e.g., to the full sized image), however, the TEI and IIIF communities have not yet agreed upon specific details of a mechanism for integrating data from these two communities of practice.

**Comment by kshawkin** [comment]
Some further rewording:

> The International Image Interoperability Framework (IIIF), with its growing user community, is likely to emerge as an alternative mechanism for linking between encoded text and images of source documents. The value of a `@facs` attribute could be a IIIF Image API Request URI (e.g., to access a full-sized image); however, note that the TEI and IIIF communities have not yet agreed upon specific details of a mechanism for integrating data from these two communities of practice.

(There are a few different APIs specified by IIIF, so we need to specify the correct one.)

**Comment by emylonas** [comment]
@sydb and I agree, let's include prose as it @kshawkin posted above.

**Comment by sydb** [comment]
Done (with some minor tweaks) at a1fc8c608ff2820df2d798915e88dfab8c7ffa8c.

**Comment by emylonas** [comment]
@sydb can we close this?

**Comment by sydb** [comment]
I think so, but thought someone else should read the para first and close it.

**Comment by emylonas** [comment]
I read it as well and it seems fine
