### ISSUE TITLE
section on FRBR?

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [kshawkin/Best-Practices-for-TEI-in-Libraries#64]
Some colleagues and I are working on recommendations for encoding FRBR relations in the TEI header, and we're wondering whether this could be published as a section within BPTL. Any opinions, anyone?

**Comment by lb42** [comment]
Would it not be useful to propose a new section in the guidelines? Then the council would have to have to agree too!

**Comment by Martin-de-la-Iglesia** [comment]
I don't know, would it really? I thought FRBR was a rather specialised and esoteric thing that maybe some librarians might be interested in, but not the TEI community at large.

**Comment by kshawkin** [comment]
I've heard FRBR mentioned a number of times over the years at TEI conferences, often by non-librarians, so there is a certain level of awareness, at least of the Group 1 entities of FRBR.  Furthermore, the Guidelines already include some library-specific information, notably http://www.tei-c.org/release/doc/tei-p5-doc/en/html/HD.html#HD8 .

My understanding, though, is that while RDA uses the FRBR Group 1 entities, the momentum in library metadata is behind a model of three entities found in BIBFRAME.  See brief discussion at https://en.wikipedia.org/wiki/BIBFRAME .  In addition, the CIDOC-CRM community found that the FRBR model could not be converted to a true object-oriented model, so they designed FRBRoo, which also does not maintain the four Group 1 entities.  In short, I don't know if we want to invest in the four FRBR Group 1 entities, even though some of us got used to thinking of the world through that lens.

**Comment by Martin-de-la-Iglesia** [comment]
It's my feeling too that Bibframe is the future, but there's still a legitimate demand for FRBR. Anyway, the solution(s) we have in mind would allow for Bibframe and FRBRoo relations too.

**Comment by kshawkin** [comment]
Okay, looking forward to seeing your solution(s).

**Comment by kshawkin** [comment]
Martin, the workgroup will meet again on Jan. 23.  Do you think you could have a proposal for us to examine by then?

**Comment by Martin-de-la-Iglesia** [comment]
Yes, that seems feasible. We'll start writing something up next week.

**Comment by Martin-de-la-Iglesia** [comment]
[Proposal text below; please discuss.]

4.1.4 The TEI Header and FRBR
-----------------------------------------------

FRBR (Functional Requirements for Bibliographic Records) is a model developed by IFLA.[1] At its core, FRBR consists of four levels - Work, Expression, Manifestation, and Item (‘WEMI’) - and the three relationships between those levels, realization, embodiment, and exemplar. Further developments based on or related to FRBR include FRBRoo (FRBR object-oriented)[2] which brings together FRBR and CIDOC-CRM, and BIBFRAME [3] which defines three levels instead of four. While the following recommendations refer to FRBR, they can be just as well applied to FRBRoo and BIBFRAME.

It has been argued that different TEI elements already implicitly refer to different FRBR levels, and that a TEI encoded document usually refers to several levels at once.[4] However, sometimes it is desirable to explicitly reference instances of different FRBR levels from a TEI document. For instance, a TEI document body may contain the text of a rare book (Manifestation), but the encoder would like to list all extant copies (Items) of this book in the header. It should be possible to make such references both as hyperlinks to external records and as full bibliographic metadata. The following three encoding recommendations address this requirement.

a) RDF style: this encoding mechanism is modeled after the `<relation>` example at <http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-relation.html#index-egXML-d53e112517> which represents the subject, predicate, and object of an RDF triple by means of the attributes `@active`, `@ref`, and `@passive`, respectively. The following example demonstrates all three possible FRBR relationships, each represented in a `<relation>` element (which is repeatable to allow for 1:n and n:n relationships):

```
<teiHeader>
    <fileDesc>
        <sourceDesc>
            <listRelation>
                <relation ref="http://purl.org/vocab/frbr/core#realization" active="http://d-nb.info/gnd/4128140-8" passive="http://d-nb.info/gnd/4217850-2"/>
                <relation ref="http://vocab.org/frbr/core#embodiment" active="http://d-nb.info/gnd/4217850-2" passive="http://d-nb.info/1022142836"/>
                <relation ref="http://purl.org/vocab/frbr/core#exemplar" active="http://d-nb.info/1022142836" passive="http://lobid.org/items/HT017412936:DE-361:NA088.88-4442721#!"/>
            </listRelation>
        </sourceDesc>
    </fileDesc>
</teiHeader>
```

b) Nested `<bibl>`: the following method is based on an approach recently presented by the Bibliotheca Hagiographica Syriaca Electronica (BHSE) project.[5] While the LAWD (Linked Ancient World Data) ontology is used in BHSE, its terms can be easily substituted by corresponding FRBR terms. As the FRBR levels can be seen as a hierarchy (a Work contains its Expressions, etc.), it makes sense to represent them as nested elements:

```
<teiHeader>
    <fileDesc>
        <sourceDesc>
            <bibl type=”http://purl.org/vocab/frbr/core#Work”>
                <bibl type=”http://purl.org/vocab/frbr/core#Expression”>...</bibl>            
            </bibl>
        </sourceDesc>
    </fileDesc>
</teiHeader>
```

The content of each `<bibl>` may consist of either a hyperlink to an external entity in `<ptr>`, or of full bibliographic metadata expressed in suitable `<bibl>` child elements.

c) `<relatedItem>`: a third option makes use of the element `<relatedItem>`, which according to the TEI Guidelines “is applied to such items as translations, continuations, different versions, parts, etc.” This appears to be a suitable element for expressing FRBR relationships. The following example shows an encoding mechanism that sits in between the RDF-like representation in a) and the semantically richer method in b):

```
<teiHeader>
    <fileDesc>
        <sourceDesc>
            <bibl>
                <relatedItem type="Exemplar" corresp="http://purl.org/vocab/frbr/core#exemplar" target="http://lobid.org/items/HT017412936:DE-361:NA088.88-4442721#!"/>
            </bibl>
        </sourceDesc>
    </fileDesc>
</teiHeader>
```

Note that `<relatedItem>` is repeatable. Instead of a hyperlink in `@target`, a full bibliographic description may be given in `relatedItem/bibl`.

References:
[1] IFLA Study Group on the Functional Requirements for Bibliographic Records: Functional Requirements for Bibliographic Records. Final Report. 1997-2009. https://www.ifla.org/files/assets/cataloguing/frbr/frbr_2008.pdf
[2] Working Group on FRBR/CRM Dialogue: Definition of FRBRoo. A Conceptual Model for Bibliographic Information in Object-Oriented Formalism. Version 2.4. 2015. www.ifla.org/files/assets/cataloguing/FRBRoo/frbroo_v_2.4.pdf
[3] Library of Congress: Bibliographic Framework as a Web of Data. Linked Data Model and Supporting Services. 2012. https://www.loc.gov/bibframe/pdf/marcld-report-11-21-2012.pdf
[4] Kevin S. Hawkins: FRBR Group 1 Entities and the TEI Guidelines. TEI Annual Members Meeting, November 6-8 2008, London.
[5] Nathan P. Gibson and David A. Michelson: Modeling a Body of Literature in TEI. Poster presented at TEI Conference, September 26-30 2016, Vienna. http://syriaca.org/blog/wp-content/uploads/2016/09/GibsonMichelson-TEI-Poster-small.jpg

**Comment by kshawkin** [comment]
Martin, thanks for this detailed explanation.  A few things:

1) In your markup samples in (a) and (c), is it okay to replace instances of `http://purl.org/vocab/` with `http://vocab.org/`?  They all seem to redirect.

2) When editing the Best Practices document, we have tried to recommend a single way of doing things and only offer more than one way when the editors of the document could not agree on a preferred way to do it.  Are you comfortable recommending just one of these solutions?

**Comment by Martin-de-la-Iglesia** [comment]
1. It probably doesn't matter much, but the rdf:about statements in the specification at http://vocab.org/frbr/core.rdf include the purl.org part, so I would prefer to keep it too.

2. Yes, in the end it would be preferable to have only one recommendation, but I couldn't make up my mind which one. Therefore I'd like to leave that decision to the BP editors.

**Comment by emylonas** [comment]
@sydb has a mild preference for option (c) . I agree. When/If TEI addresses this, we can follow their recommendation.

Where would this go? which levels does it apply to? do we have bibliography in BPTL sections?

**Comment by sydb** [comment]
I also think it is probably important to cite the seminal paper on this topic: [Renear’s 2003 paper](http://conferences.idealliance.org/extreme/html/2003/Lawton01/EML2003Lawton01.html) (or the [PDF thereof](https://www.ideals.illinois.edu/bitstream/handle/2142/11885/Renearetal03.pdf?sequence=2))

**Comment by kshawkin** [comment]
Syd and I discussed today, and he's having second thoughts about (c).  He's going to propose a modification of this code sample for us.  If we're good with it, we'll incorporate into the BPTL.

By the way, we assume that Martin's suggestion above (for section 4.1.4) is meant to be a new section inserted before the current section 4.1.4.

**Comment by sydb** [comment]
How about just changing `@corresp` (which means roughly “this `<relatedItem>` corresponds to that thing over there in some specific, e.g. one-to-one, relationship”) to `@ana` (which means roughly “it is my analysis of this `<relatedItem>` that it has something to do with that thing over there”); in this case, that thing over there expresses the kind of relationship this `<relatedItem>` has to … what, the entire TEI document or the bibliographic item described by its parent `<bibl>`?

**Comment by kshawkin** [comment]
I believe that a `relatedItem` nested inside a `bibl` should be interpreted to express a relationship to its parent `bibl`, not the entire TEI document.  That would be consistent with how TEI markup is generally interpreted.  Syd, is there any reason you would think that `relatedItem` would express a relationship to the entire TEI document?

**Comment by Martin-de-la-Iglesia** [comment]
@kshawkin Yes, I meant this new section to go roughly where 4.1.4 is now in the current BP document.

@sydb I thought I had read somewhere that `@corresp` would be suitable for RDF-style predicates, but I'm not so sure about it anymore. `@ana` seems fine too.

**Comment by lb42** [comment]
Jusdt a quick comment as I havent had time to read the proposed text carefully: is this going to be a new section for the Guidelines or for the BP document? Because if the former (which was my original suggestion), there's no need to choose one of the recommended methods. Au contraire: the Guidelines should present the full variety of what makes sense, with the merits and demerits of each.

**Comment by kshawkin** [comment]
Thank you for the reminder of your earlier suggestion to include something in the Guidelines.  This GitHub project is concerned only with the BP document, so that's where we plan to make a change.  Martin is free to propose changes to the Guidelines as well, or the Technical Council could take that up on their own initiative.

**Comment by Martin-de-la-Iglesia** [comment]
... or the Libraries SIG could rework my BP draft into a Guidelines draft.

**Comment by kshawkin** [comment]
After discussion, Syd, Elli, and Kevin decided that we like solution (a).  I will implement.

**Comment by kshawkin** [comment]
Elli and I will review the HTML output on Syd's server.

**Comment by kshawkin** [comment]
Syd has regenerated the HTML: http://paramedic.wwp.neu.edu/~syd/temp/BPTL/main-driver.html .  There are rendering bugs relating to bibliographic citations, but overall I think the necessary content is there.  Over to Elli to review as well.

**Comment by emylonas** [comment]
Proofreading: 


- In the two references in the first sentence, should the parenthesized name follow the un-parenthesized name? I would keep the abbreviations in the parentheses, following the full name. Maybe just switch the `<abbr>` and `<expan>`? 
- Link for IFLA `https://www.ifla.org/`
- URL for Functional Requirements for Bibliographic Records: Final ReportFebruary 20097 `https://www.ifla.org/files/assets/cataloguing/frbr/frbr_2008.pdf` also - date is 2009, first version is 1997. 
- FRBRoo and BIBFRAME - treat like citations above? Full name followed by abbreviation? or not necessary? 
- "Note that a TEI document itself, like any other XML document, has an ambiguous status between a FRBR expression and a FRBR manifestation." Do you mean "occupies an ambiguous territory"? "reflects and ambiguous role"? "falls between"?
- let's talk through the `@active` and `@passive` one last time to make sure they are correct.They seem backwards.

**Comment by Martin-de-la-Iglesia** [comment]
> let's talk through the @active and @passive one last time to make sure they are correct.They seem backwards.

They're correct. http://vocab.org/frbr/core#realization means, "has realization", etc.

**Comment by emylonas** [comment]
great. that's the kind of 'englishing" that I need to get it straight in my head.

**Comment by emylonas** [comment]
@kshawkin makes corrections as above

**Comment by kshawkin** [comment]
I've addressed all of Elli's suggestions except treating FRBRoo and BIBFRAME as abbreviations.  I can't find anywhere but Wikipedia that explicitly expands "FRBRoo" (as obvious as it may be), and BIBFRAME is similarly not defined as standing for anything in particular.  So I think those are fine.
