### ISSUE TITLE
new section on METS

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#66]
We should review this pull request:

https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/pull/65

**Comment by sydb** [comment]
Pull request merged, now we have a bit of tweaking to do.

**Comment by emylonas** [comment]
from pull request comments, about tweaking:
@sydb  and I looked it over. It's fine to merge. However, post merge, would make following tweak: 
change `that is complete  <gi>teiHeader</gi> tags can be included in METS metadata alongside MARC, MODS and DC. METS specifies 'TEIHDR' to indicate a TEI Header. `
to
` that is a complete <gi>teiHeader</gi> element can be included in METS metadata alongside MARC, MODS and DC. METS specifies 'TEIHDR' to indicate a TEI Header. `

**Comment by sydb** [comment]
I actually did some more significant re-wording. Commited at a1fc8c608ff2820df2d798915e88dfab8c7ffa8c. Take a look. As often, there is a temporarily available [HTML version](https://bauman.zapto.org/~syd/temp/BPTL/main-driver.html) to read.

**Comment by emylonas** [comment]
@sydb did you take a look at section 3.8:
`For those projects relying on the Metadata Encoding and Transmission
Standard (METS), the xml:id attribute is used as a conceptual identifier
for content as opposed to an explicit pointer (i.e., facs attribute) to a
specific representation of that content. These identifiers are then used to
generate a METS document that bundles the various content types (e.g.,
master image files, derivative image files for Web delivery, PDFs, etc.),
explicitly lists all versions of the content, and defines the relationships
between the constituent parts. This is achieved through the use of the
<mets:fileSec> and <mets:structMap> sections of the METS document (see
sample METS document for a TEI project).`

do we need to refer back and forth?

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

**Comment by lb42** [comment]
" is used as a conceptual identifier for content as opposed to an explicit pointer (i.e., facs attribute)" is a bit clumsy. How about "provides an identifier for a piece of content, but does not reference any specific representation of it"

**Comment by emylonas** [comment]
Lou's comment is a new issue as he is suggesting a rewording for a different part of the BP.

I read over the work that @sydb was doing on this issue, and there are two oddities that I've found
 
- `METS specifies an OTHERMDTYPE of TEIHDR to indicate a TEI Header.` is wrong. The `TEIHDR` value belongs on 'MDTYPE` not 'OTHERMDTYPE` which is for the case where `@MDTYPE="OTHER"`. Someone please check, I looked here: [http://www.loc.gov/standards/mets/docs/mets.v1-9.html#mdWrap](http://www.loc.gov/standards/mets/docs/mets.v1-9.html#mdWrap)
- The Cookery book example link doesn't work. Not sure if it was sent along with the revised prose or what, but we should make sure we have our hands on it. I can't check the original BPTL as this is a new section/new link.  The filename we are looking for is: `edmcook-original_mets_xmp.xml`

**Comment by sydb** [comment]
I’ll look at the first in a minute. But as for the second, that file is [check in](https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/blob/master/BestPractices/edmcook-original_mets_xmp.xml). From where does the link not work?

**Comment by emylonas** [comment]
fixed and closed with commit  5920db4
