### ISSUE TITLE
give guidance on incorporating outside metadata into a header

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#7]
The TEI Technical Council is finalizing a recommendation for a new element (tentatively named `<xenoData>`: https://github.com/TEIC/TEI/issues/453 ).  Once this is included in P5, we should at least mention it if not also give more specific guidance on its use.

Note that this change will require that https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/2 be resolved first.

**Comment by kshawkin** [comment]
That element was included in P5 2.9.0, but there are some things still to be worked out: https://github.com/TEIC/TEI/issues/1346 .

**Comment by sydb** [comment]
Nothing left to work out in P5 that should prevent us (or even slow us down) from recommending `<xenoData>`. It was made for this group (librarians, not necessarily BP), after all.

**Comment by sydb** [comment]
The prose of lib-header.odd that needs to be re-written is (or, at least part of what needs to be rewritten):  

> Unfortunately, there is currently no mechanism for specifying that the content of an element should be drawn from an outside metadata source or that this outside metadata source should supplement the content of the element. In the absence of such mechanisms, users of these <title>Best Practices</title> may use the <gi>idno</gi> element to supply identifiers for outside metadata records and may supply identifiers for certain authority records using the <att>ref</att> attribute, allowed on certain elements.

**Comment by kshawkin** [comment]
In January we decided that I would draft the revision to share, but once I looked at it, I decided it is actually straightforward.  So I've implemented: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/e3bbd774215424ee3a35276072238b93f9377eaf .
