### ISSUE TITLE
clean up our source citations

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#71]
Various ODD files composing the BPTL use `<bibl>` (and maybe `<biblStruct>`?) to cite sources in our prose or examples.  There are a few problems:

1. The ODD-to-HTML stylesheet that we are using does not insert any separating punctuation, but we have neglected to insert it in all cases.  (To see examples, search for "bondage" in the the HTML version of the BPTL.)
1. We've been inserting these `<bibl>`s right after the source, and the stylesheet renders them right there inline, which looks okay after a code sample but not in other places (like the citation inserted at https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/63bc9c61dd9b901904108575c9e70469020406ad ).  We should probably gather these into an endnotes section.
1. We've been inconsistent in our citation style for these sources.  We should settle on something (MLA?  one of the two Chicago styles?) and reformat as needed.

**Comment by kshawkin** [comment]
Try changing `egXML@corresp` into `egXML@source` and see if they render better.

As for citation inserted at https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/63bc9c61dd9b901904108575c9e70469020406ad , I should wrap the `bibl` in a `note`.

**Comment by kshawkin** [comment]
Now ready for @sydb to regenerate HTML to test rendering.  Maybe this will fix point (2) in this issue.

**Comment by sydb** [comment]
Generated. (Sorry for delay.) I put the results on my [desktop](http://paramedic.wwp.neu.edu/~syd/temp/BPTL/).

**Comment by kshawkin** [comment]
At https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/ff6a1670963647ce2f8d516d737f34a785a0937a , https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/23074ea83f307e85c8c5fbec4a859e7a3713bb38 , and https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/c54bc4d330ee37634ac2a88cd84285901a447ca3 , I've wrapped remaining `bibl`s in `note`s and formatted according to Chicago style (citations using author-date method).
