### ISSUE TITLE
content model for <relatedItem>

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#73]
Our table of header elements provides the option of using `<relatedItem>` for a work related to the source document.  There is one child element given (`<bibl>`), with two children of its own: `<author>` and `<title>`.  Two questions:

1. Why did we decide to use `<bibl>` here and not `<biblStruct>`, which is what the `<relatedItem>` is contained in?
1. Why did we only list `<author>` and `<title>` as the descendants of `<relatedItem>`?  You might, for example, want an `<idno>` as well.  Here's an example from @lb42 : you want to give bibliographic info for both the print original and a scanned version of that original (one of which is the source of the encoding), so one of these would go in `<relatedItem>`.  The print original has a shelf mark or call number, whereas the digitized version has a digital identifier.

**Comment by lb42** [comment]
The more I look at this far from uncommon case, the more intractable it seems., Take a look at the metadata associated with an Internet Archive catalogue entry. Where and how do you propose to record all these items? Here's an example:
                                Collection europeanlibraries
                                Digitizing sponsor Google
                                Book from the collections of Oxford University
                                Language English
                                Book digitized by Google from the library of Oxford University and uploaded to the Internet Archive by user tpb.
                                Copyright-region US
                                Identifier passagesinlifea02greygoog
                                Identifier-ark ark:/13960/t9x06bj3p
                                Pages 327
                                Possible copyright status NOT_IN_COPYRIGHT
                                Scandate 20060712
                                Scanner google
                                Source http://books.google.com/books?id=G8YBAAAAQAAJ&amp;oe=UTF-8
                                Worldcat 13304185

**Comment by kshawkin** [comment]
For anyone interested, it seems that Lou's example comes from https://archive.org/details/passagesinlifea02greygoog .

Let's say that you are creating a TEI document using this scanned version.  According to the Best Practices, metadata relating to the scanned version would go in TEI/fileDesc/sourceDesc/biblStruct, whereas metadata relating to the print original could be put in TEI/fileDesc/sourceDesc/biblStruct/relatedItem.

You'll need to determine which metadata elements here refer to the scanned version, which to the print original.  Some may apply to both, and others could be ambiguous (e.g., were there 327 pages in the print original or are there 327 scanned page images?).

Do you have any ideas for guidance not specific to metadata from the Internet Archive that we could add to the BP?

**Comment by kshawkin** [comment]
Elli and Kevin agreed to replace relatedItem/bibl with relatedItem/biblStruct, explaining that you should encode as biblStruct is described as above.  Move the mappings currently given for relatedItem/bibl/author and relatedItem/bibl/title into relatedItem/biblStruct but don't go into much detail.

Kevin will make prose changes and then reassign to Syd for schema changes.

**Comment by sydb** [comment]
Not sure there is a schema change to be made. At level 1 or 2 the content of `<relatedItem>` is one of
`<bibl>`, `<biblStruct>`, `<ptr>`, or `<ref>`. At levels 3 and 4 we add `<listBibl>` to the mix. So `<biblStruct>` is already allowed as a child. (Do we actually want to remove `<bibl>`?)

**Comment by kshawkin** [comment]
Yes, we should remove `<bibl>` as a child of `<relatedItem>`.

**Comment by sydb** [comment]
OK. This is not difficult, but nor is it trivial, as `<bibl>` is not a child of `<relatedItem>` directly, but rather by means of being a member of model.biblLike. It is also a member of model.biblPart, but that only allows it to self-nest. Its memebership in model.biblLike allows it to be used in many places, for a complete list of which see an analysis below.

The analysis reveals, I think, two things:

1. Removing `<bibl>` from `<relatedItem>` is not crazy. A bit weird, in that it can go in `<taxonomy>` and `<change>`, but not crazy.

2. The `<quote>` element is in levels 1, 2, and 4, but not level 3, which is obviously wrong.


## below

### simple list
**level 1**:  bibl cit emph item note p q quote ref relatedItem title change licence rendition taxonomy

**level 2**: bibl cit emph head item note p q quote ref relatedItem title change licence rendition taxonomy

**level 3**: bibl cit emph head hi item l listBibl note p q ref relatedItem title cell figure change licence rendition taxonomy ab  div div1 div2 div3 div4 div5 div6 div7

**level 4**: add bibl corr del desc emph head hi item l listBibl note p quote ref relatedItem said sic stage title unclear castList cell figDesc figure change licence rendition taxonomy ab person argument div div1 div2 div3 div4 div5 div6 div7 docEdition epigraph postscript salute signed titlePart trailer

### compressed list
Which, using entity references to make a bit easer to read, is:

**level 1**: bibl cit emph item note p q quote ref relatedItem title change licence rendition taxonomy

**level 2**: _&level1;_ + head

**level 3**: _&level2;_ -quote + hi l listBibl cell figure ab div div1 div2 div3 div4 div5 div6 div7

**level 4**: _&level3;_ + add corr del desc quote said sic stage unclear cell figDesc ab argument docEdition epigraph postscript salute signed titlePart trailer

### table by level
Or, in a table sorted by level:

GI         | L1 | L2 | L3 | L4 
-----------|----|----|----|----
bibl       | ✅  | ✅  | ✅  | ✅
cit        | ✅  | ✅  | ✅  | ✅
emph       | ✅  | ✅  | ✅  | ✅
item       | ✅  | ✅  | ✅  | ✅
note       | ✅  | ✅  | ✅  | ✅
p          | ✅  | ✅  | ✅  | ✅
q          | ✅  | ✅  | ✅  | ✅
quote      | ✅  | ✅  |    | ✅
ref        | ✅  | ✅  | ✅  | ✅
relatedItem     | ✅  | ✅  | ✅  | ✅
title      | ✅  | ✅  | ✅  | ✅
chage      | ✅  | ✅  | ✅  | ✅
licence    | ✅  | ✅  | ✅  | ✅
rendition  | ✅  | ✅  | ✅  | ✅
taxonomy   | ✅  | ✅  | ✅  | ✅
head       |    | ✅  | ✅  | ✅
hi         |    |    | ✅  | ✅
l          |    |    | ✅  | ✅
listBibl   |    |    | ✅  | ✅
cell       |    |    | ✅  | ✅
figure     |    |    | ✅  | ✅
ab         |    |    | ✅  | ✅
divS       |    |    | ✅  | ✅
add        |    |    |    | ✅
corr       |    |    |    | ✅
del        |    |    |    | ✅
desc       |    |    |    | ✅
said       |    |    |    | ✅
sic        |    |    |    | ✅
stage      |    |    |    | ✅
unclear    |    |    |    | ✅
cell       |    |    |    | ✅
figDesc    |    |    |    | ✅
argument   |    |    |    | ✅
docEdition |    |    |    | ✅
epigraph   |    |    |    | ✅
postscript |    |    |    | ✅
salute     |    |    |    | ✅
signed     |    |    |    | ✅
titlePart  |    |    |    | ✅
trailer    |    |    |    | ✅

### table by element name
Or, in a table sorted by element name:

GI         | L1 | L2 | L3 | L4
-----------|----|----|----|----
ab         |    |    | ✓  | ✓
add        |    |    |    | ✓
argument   |    |    |    | ✓
bibl       | ✓  | ✓  | ✓  | ✓
cell       |    |    |    | ✓
cell       |    |    | ✓  | ✓
chage      | ✓  | ✓  | ✓  | ✓
cit        | ✓  | ✓  | ✓  | ✓
corr       |    |    |    | ✓
del        |    |    |    | ✓
desc       |    |    |    | ✓
divS       |    |    | ✓  | ✓
docEdition |    |    |    | ✓
emph       | ✓  | ✓  | ✓  | ✓
epigraph   |    |    |    | ✓
figDesc    |    |    |    | ✓
figure     |    |    | ✓  | ✓
head       |    | ✓  | ✓  | ✓
hi         |    |    | ✓  | ✓
item       | ✓  | ✓  | ✓  | ✓
l          |    |    | ✓  | ✓
licence    | ✓  | ✓  | ✓  | ✓
listBibl   |    |    | ✓  | ✓
note       | ✓  | ✓  | ✓  | ✓
p          | ✓  | ✓  | ✓  | ✓
postscript |    |    |    | ✓
q          | ✓  | ✓  | ✓  | ✓
quote      | ✓  | ✓  |    | ✓
ref        | ✓  | ✓  | ✓  | ✓
relatedItem     | ✓  | ✓  | ✓  | ✓
rendition  | ✓  | ✓  | ✓  | ✓
said       |    |    |    | ✓
salute     |    |    |    | ✓
sic        |    |    |    | ✓
signed     |    |    |    | ✓
stage      |    |    |    | ✓
taxonomy   | ✓  | ✓  | ✓  | ✓
title      | ✓  | ✓  | ✓  | ✓
titlePart  |    |    |    | ✓
trailer    |    |    |    | ✓
unclear    |    |    |    | ✓

**Comment by kshawkin** [comment]
Use this for ODD for `<relatedItem>`:

`
<elementSpec module="header" ident="relatedItem" mode="change">
	    <content>
	      <elementRef key="biblStruct"/>
	    </content>
	  </elementSpec>
`

Remove `<quote>` from levels 1 and 2: they are not references at those levels.

**Comment by sydb** [comment]
OK. `<quote>` has been removed from levels 1 & 2 (which I did weeks ago), and the content of `<relatedItem>` is now required to be 1 and only 1 `<biblStruct>` (at every level, which I just did now). I find that a bit distressing … isn’t it reasonable to want to say “that web resource over there is a related item”? In which case either having 0 or 1 `<biblStruct>` (and using `@target` — and note that P5 already includes a constraint that if `@target` is present the `<biblStruct>` must be empty, and that either `@target` or content should be present) OR leaving `<ptr>` and `<ref>` as possible content makes sense. 

Use of `<ref>` gives the encoder the capability to add a snippet of prose not otherwise allowed (i.e., not allowed with the `@target` or `<ptr>` methods). E.g.
~~~~~xml
<relatedItem>
  <ref target="http://www.example.edu/repository/scannedStuff/whatevere2/page0.jpg">Scanned page images of the 2nd edition</ref>
</relatedItem>
~~~~~

**Comment by sydb** [comment]
@kshawkin points out that it is good practice to include a full bibliographic citation even if the related item **is** a web resource. In which case, 1 and only 1 `<biblStruct>` makes sense, but `@target` does not.

Thus, I’ve removed `@target` (and the `<constraintSpec>` about it) from `<relatedItem>`.

Note that @kshawkin is making a new issue for discussing _how_ to encode the URL inside the `<biblStruct>`.

Close this issue as soon as we build and make sure changes worked.

**Comment by kshawkin** [comment]
For the record, the new issue that Syd mentioned two days ago has now been created: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/83
