### ISSUE TITLE
How does a document specify its level of encoding?

### ISSUE THREAD

**Issue by lb42** [kshawkin/Best-Practices-for-TEI-in-Libraries#74]
Unless I missed it (which is quite possible) there isn't any recommendation here on  how a document should specify the bp-level of its encoding. Would this not be useful?  Maybe something as simple as &lt;encodingDesc n="BP-level-1"/&gt; would do.

**Comment by kshawkin** [comment]
What you're looking for is encodingDesc/schemaRef key='BPTL-L1-v3.4.2a'.

**Comment by lb42** [comment]
Ah, thanks. I thought you must have done it already! Though strictly this is refererring to a specific version release of BPTL, rather than the generic "level1" I had in mind.

**Comment by kshawkin** [comment]
The BPTL used to refer to the generic levels through editorialDecl@n, but we changed our mind about this: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/17

**Comment by lb42** [comment]
I should have guessed that troublemaker @lb42 started this... are you aware that, as currently defined in P5. schemaRef apparently has a mandatory @URL attribute as well as @key ?

**Comment by kshawkin** [comment]
I was not, but now I am!
