### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#75]
Should this say `version="4.0.0a"` as elsewhere?

https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/blob/da6db9b12f921b137dc43d332f2a41f744e3a339/BestPractices/main-driver.odd#L6

**Comment by sydb** [comment]
Nope. That's the version # of P5 which the ODDs conform to. We have three version #s, and sadly they are all very close to one another:
* The above, the version # of P5 against which our ODD files are supposed to be valid. Specified on the `@version` of the outermost `<TEI>` element, currently "3.1.0". (Probably should update to 3.3.0 at some point, I suppose, but there’s no rush.)
* The version # of P5 against which our ODD files are built — that is, we are writing a customization, but a customization of what version of the base P5? This is specified on the `@source` of `<schemaSpec>`, and is currently "tei:3.3.0". We should try to keep this pretty close to up-to-date.
* The version number of our customization, which is current "4.0.0a".

**Comment by kshawkin** [comment]
Okay, thanks for clarifying.  I guess this is all follows how these elements and attributes are documented in P5.  If, however, any of this is not explicit in P5, it might be worth adding comments to the ODD source to clarify the distinctions in the bullets above.  Doing so would save ourselves headaches later when we go through and want to update the version number of the BPTL ... or validate against a newer version of P5.

**Comment by kshawkin** [comment]
We should also not forget about the version number(s) given next to each name in the acknowledgements section!

**Comment by emylonas** [comment]
@kshawkin  add the version numbers next to the names

**Comment by kshawkin** [comment]
The names already have version numbers next to them; I just meant that the XML comments to remind us about these things as well.

But, anyway, I will implement the issue, adding XML comments to annotate each of the things that Syd enumerated to help us keep these things straight in the future.
