### ISSUE TITLE
Add element for explicitly indicating license

### ISSUE THREAD

**Issue by sydb** [kshawkin/Best-Practices-for-TEI-in-Libraries#77]
The TEI `<licence>` element can be used as a child of `<availability>` to explicitly indicate under what license a user could copy and use a TEI document. E.g.:

~~~~~xml
        <availability status="restricted">
          <p>Copyright 2007 Syd Bauman, Julia Flanders, and Northeastern WWP</p>
	  <licence>This TEI-encoded XML file is available under the terms of
 	  the <ref target="http://creativecommons.org/licenses/by-sa/3.0/">Creative
	  Commons Attribution-ShareAlike 3.0 (Unported)</ref>
	  license.</licence>
        </availability>
~~~~~

Off the top of my head, I do not see why BPTL would not include this element. Certainly I would like it to be included, as I use it frequently, and I believe the Charon project would want to use it.

**Comment by emylonas** [comment]
Agree, useful element. prefer to have `<p>` and `<license>`

**Comment by emylonas** [comment]
EM will rewrite table cell so as to remove ref to `<p>` in the `<availability>` box and add references to `<p>` and`<license>` in the prose para. Assigning to Kevin for feedback.

@sydb has added `<license>` to the schema

**Comment by kshawkin** [comment]
This all sounds good.  I believe that `<license>` has been missing from the BPTL because it was added to P5 after October 2011, when the last version of BPTL was published.

**Comment by emylonas** [comment]
close once guidelines have been remade and checked

**Comment by kshawkin** [comment]
Reviewed and made a few more tweaks.
