### ISSUE TITLE
section heading should have `@ref`

### ISSUE THREAD

**Issue by emylonas** [kshawkin/Best-Practices-for-TEI-in-Libraries#87]
http://paramedic.wwp.neu.edu/~syd/temp/BPTL/2018-07-10T11/bptl-driver.html#index.xml-body.1_div.3_div.9_div.3 should read
`3.9.3. @ref and tag URIs`
i think?
will fix unless unnecessary

**Comment by kshawkin** [comment]
Yes, please change `<head>ref and tag URIs</head>` to `<head><att>ref</att> and tag URIs</head>` !

**Comment by emylonas** [comment]
fixed and closed with e41a02b
