### ISSUE TITLE
intertwingled content in <editorialDecl>

### ISSUE THREAD

**Issue by kshawkin** [kshawkin/Best-Practices-for-TEI-in-Libraries#9]
P5 now allows a mix of paragraphs and specialized elements as children of `<editorialDecl>` ( https://github.com/TEIC/TEI/issues/818 ), but we somehow missed this change when working on the BP.  We didn't realize this for version 3.0 of the BP, and since we wanted to include data that wouldn't fit in one of the specialized elements, we recommended putting everything in `<p>` elements.  We should undo this mistake.  Recommend use of specialized elements where possible, with `<p>` just used for anything that doesn't fit into one of those elements.

**Comment by kshawkin** [comment]
During BPTL call today, @arouner agreed to implement this by September call.

**Comment by kshawkin** [comment]
@arouner wrote to me today to ask for an extension till November unless he's holding us up.  He's not (there's still plenty of time!), so I'll leave the assignment with him.

**Comment by kshawkin** [comment]
@arouner said he won't be able to get to this anytime soon, so it might be best to reassign to someone else.

**Comment by kshawkin** [comment]
During today's BPTL call, Syd said that he thought he had completed this but would need to check.

**Comment by sydb** [comment]
Schema work is completed (at dffbeb5ca583ec69c53158d8671e92ffac74683c or earlier): it does indeed permit intertwined specialized elements and paragraphs (or anonymous blocks) in `<editorialDecl>`. The table in `lib-header.odd` still needs to be updated, as it does not have entries for the specialized elements: `<correction>`, `<hyphenation>`, `<interpretation>`, `<normalization>`, `<punctuation>`, `<quotation>`, `<segmentation>`, and `<stdVals>`; and the prose for `<editorialDecl>` (which I’ve flagged in red) still mentions `@n` and uses `<p>` where special elements should be used.

**Comment by kshawkin** [comment]
During the BPTL meeting on 2017-02-13, I suggested that Syd only bother including those specialized elements that would be required in order to address the items in the bulleted list for `<editorialDecl>` in the "big header table".

**Comment by emylonas** [comment]
During the BPTL meeting, we agreed to remove `<interpretation>`, `<stdvals>`, and `<segmentation>`, leave red question marks in MARC record column, and remove last two bullet points under `<editorialDecl>`

**Comment by sydb** [comment]
Done at bdccd5c.

**Comment by kshawkin** [comment]
In lib-header.odd, we've imposed a sequence on members of a class to require users to put them in the order listed in the big header table—see, for example, the `elementSpec` for `encodingDesc`.  Given that, I think we should do the same for `editorialDecl`, requiring the following content model (in DTD syntax):

p, p, p, p, p, p, correction, hyphenation, normalization, punctuation, quotation

**Comment by sydb** [comment]
Have to say I'm not crazy about this idea. Nonetheless, implemented at baa8dd1.

**Comment by lb42** [comment]
This looks bonkers to me. If you want to allow p to intertwingle with the other more specialised elements rather than be used as an alternative to them then you can't at the same time require an order for the latter without imposing an order on the former.  Your current model insists that any p has to precede the other elements so it's not interwingling at all. I say nothing of the ridiculousness of imposing a limit on the number of model.pLike elements you will permit.

**Comment by kshawkin** [comment]
The title of this issue is misleading now that we settled on using five the specialized child elements plus five `p` elements for things not addressed by specialized elements.  So disregard any notion of "intertwingling" in thinking about what Syd has implemented.

**Comment by emylonas** [comment]
@kshawkin @sydb let's discuss this in our next call for a few minutes.

**Comment by sydb** [comment]
True, but @lb42 still has somewhat of a point. Unless we are actually going to require there be exactly 6 `<p>` elements to represent the 6 bullet points in the table, even if some of them are empty, there is no way for software to automatically extract even the correct bit of prose. In which case, there is no particular reason to require that there be a one-to-one relationship between paragraphs and subject matter. Given that the subject matter is not likely to be something that can be acted on in an automated way anyway, I don’t see the advantage of being so restrictive.

Worth noting, BTW, that I presumed when implementing that each sub-part of the `<editorialDecl>` should be optional. I.e., in DTD syntax
~~~~~
     (model.pLike?,
      (model.pLike,
       (model.pLike,
        (model.pLike,
         (model.pLike,
          (model.pLike, model.pLike?)?)?)?)?)?),
     correction?,
     hyphenation?,
     normalization?,
     punctuation?,
     quotation?
~~~~~
(Note that all those parens and question marks are just to avoid non-determism; it just means each `<p>` (or `<ab>`) is optional.)

So we can discuss this on the call, but my instinct is that if we want to be more restrictive than P5, just 
~~~~~
model.pLike*, correction?, hyphenation?, normalization?, punctuation?, quotation?
~~~~~
would be as different as I would get. And I may be mis-remembering, we may require use of `<p>`, not `<ab>` in the header, in which case change `model.pLike` to `p`.

**Comment by lb42** [comment]
Why don't you introduce new elements for the  five "things not addressed by specialized elements" if you know what they are? If not wouldn't it be better to use &lt;ab> than &lt;p>, since it has a @type attribute?

**Comment by emylonas** [comment]
I agree that @lb42 has a point, and even more so when you see that @sydb 's implemention makes the `<p>` elements optional and doesn't require there to be 6. Unless we are worried about backwards compatibility, I'd go with the TEI definition of encodingDecl, perhaps removing `<p>` and using `<ab>` instead. And we could consider adding type attributes. But not necessarily. Most of this isn't going to be either processable or enforceable.

**Comment by sydb** [comment]
I also like `<ab>` with a (required) `@type`, except that (IIRC) we have previously decided to only use `<p>` in the TEI header, never `<ab>`.

**Comment by lb42** [comment]
Maybe that's a decision worth reviewing? It has always seemed to me that blocks of text in tnhe header are not really paragraphs in the same way as paragraphs in the body of a text are....

**Comment by sydb** [comment]
I agree, both because
a) `<p>` elements in the body of a text are descriptive: “I see a paragraph here”. `<p>` elements in the header are speech acts: “I hereby tell you this thing is a paragraph”.
a) some “paragraphs” in the header do not actually meet the usual criteria for paragraphs

**Comment by lb42** [comment]
Well, all markup is a kind of speech act, whether in the header or elsewhere. Seems to me that the chunks of text you find in the header are not present in the document being encoded, but added to it (they might come from some other document, of course, which complicates the argument). But in general it is quite likely that they wont be structurally or semantically the same as chunks of text in the body of the document., if only because you don't have a source document to which you can attribute "paragraphness". For example 
~~~~
<sourceDesc><p>No source</p></sourceDesc>
~~~~
However, this is an argument I've made before and lost. As have others (notably Jean Veronis). And it would instantly break almost every existing TEI document to disallow &lt;p> in the header.

**Comment by kshawkin** [comment]
We decided in April 2017 to allow only `<p>` instead of only `<ab>`: https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/issues/56 .  We don't have minutes from that meeting, but I think we felt that distinguishing between complete sentences and fragments was unimportant to users of the BPTL, and we were reluctant to break with longstanding practice of using `<p>`s within the header even for sentence fragments.

**Comment by kshawkin** [comment]
During discussion during BPTL call today, we decided:

1. Fix "│" and "├" on line for `editorialDecl/p`.
1. Move the row on `editorialDecl/p` to be after the specialized child elements of `editorialDecl`.
1. Move the first bullet under `editorialDecl/p` to be the last and reword to say something like "any other editorial decisions".
1. Revise sentence introducing the bullets to say something like "Include up to one `p` element for each of the following, in the order given:"
1. Update content model to have a minimum of 0 and a maximum of 6 `p` elements.
